mp/game/neo/scripts/weapon_grenade.txt, mp/game/neo/scripts/weapon_knife.txt, mp/game/neo/scripts/weapon_remotedet.txt, mp/game/neo/scripts/weapon_smokegrenade.txt, mp/src/game/shared/basecombatcharacter_shared.cpp, mp/src/game/shared/gamerules.cpp
Grenades, smoke grenades and det-packs are now removed from the players inventory once they run out of ammunition, allowing for more of these items to be picked up either off of the ground or through the give weapon_x command
=> Removed utility on exhaust, re-added auto weapon switching

mp/src/game/shared/basecombatcharacter_shared.cpp
Dropping the weapon seems to cause it as of current main branch.
=> Fix NULL dereference on pCurrent (SwitchToNextBestWeapon)

mp/src/game/shared/baseentity_shared.cpp
Disabling some client biasing code to make fully automatic weapons usable when playing with ping
=> Weapon Handling in multiplayer work-around

mp/src/game/shared/neo/neo_mount_original.h
Fix the silly "cannot find neopath" error message when closing the game on windows
=> Removed cannot find neopath messages on windows application shutdown

mp/src/game/client/c_baseplayer.h, mp/src/game/client/hl2/hl2_clientmode.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/client/view.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/server/player.cpp, mp/src/game/server/player.h, mp/src/game/shared/baseplayer_shared.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/shareddefs.h
* Most importantly, weapon switching shouldn't use pre-set fov default, because somehow convar isn't updated (client variable) even though it's updated (server and console recognizes)?????
* New convar: `neo_fov`, default 90, range 60-110
=> Configurable FOV/Field of view, new convar: neo_fov

mp/src/game/server/gameinterface.cpp
If set to EX: 120, then the server will warn/log:
`WARNING: Setting -tickrate is not recommended. Server is only recommended to run at the default ~66.67 tickrate. Current tickrate: 120`
=> Warn if -tickrate is set

mp/src/game/server/neo/neo_player.cpp
* Now available as server convars:
* `sv_neo_change_suicide_player` - Default to 0/false
* `sv_neo_change_threshold_interval` - Default of 0.25 seconds, down from previous 5 seconds
* Default `sv_neo_change_suicide_player` to false which was previously true. This also adds a functionality to prevent player change on player being alive.
=> Team switching - Make it available as server convar, change defaults

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_marker.h
Dunno why this part of the code got deleted during the hud/positioning change
=> Revert accidental code deletion - Ghost marker should be red on enemy

mp/src/game/shared/neo/weapons/weapon_supa7.cpp
* Yes, the slug uses primary animation while the main one uses secondary animation
=> Supa7 - Fix animation usage between slug and primary

mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/player.cpp
disables some hl2dm code in player death think that meant code to check if player should respawn or enter observer mode was never reached. Also now listening for player input before entering observer mode, can enter observer mode no earlier then after the death animation time is over (about 3 seconds)
=> Observer on demand

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp
Can't move slower than 56 HU in ogtokyo, this change caps the lower speed limit to 56 HU
=> Speed lower cap

mp/src/game/shared/neo/neo_gamerules.cpp
Execute client command for clients to clear all decals, is there a better way to do this?
=> Clear decals on round start

mp/game/neo/scripts/weapon_srs.txt, mp/src/game/shared/neo/neo_player_shared.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h, mp/src/game/shared/neo/weapons/weapon_srs.cpp, mp/src/game/shared/neo/weapons/weapon_srs.h
Adds bolting the srs, prevents bolting and reloading when looking through scope and fire button is held, bolting animation supersedes running animation, weapons dropped before being bolted do not have a round in the chamber and have to be chambered on pickup
=> Srs Bolting

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/hl2/hl2_usermessages.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/neo/neo_player_shared.cpp, mp/src/game/shared/neo/neo_player_shared.h
* Shows damage, hits, and killer info at round end or death
* Shows in both the (server process, client shown) left-side menu and (client process + shown) console
* If it overflows in left-side menu (because it has 512bytes size limit), it'll appear in multiple pages
* If killed instead of round end/self-killed, then it'll also show up killer's information
=> Damage + hits + killer info on death/round end

mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
* `neo_round_limit` - Default 0/off, if set, maximum amount of round can be played per match
* `neo_round_sudden_death` - Default 1/on, if set, going over `neo_round_limit` if `neo_round_limit` is not 0 will cause the next round on sudden death on ties until a winner happens
* Added an indicator on round that is sudden death
* This also removed some block of code which I think is unused now
=> Implement round limit, early win, match point indicator, and sudden death

mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/weapons/weapon_grenade.cpp, mp/src/game/shared/neo/weapons/weapon_knife.cpp, mp/src/game/shared/neo/weapons/weapon_knife.h, mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
* Refactored the knife to use `CNEOBaseCombatWeapon` as its based class, pulled over some melee specific stuff over
* Refactored on functions that differentiates the knife when it wasn't a Neo-weapon
* When sprinting, use the sprint animation. Fixes https://github.com/NeotokyoRebuild/neo/issues/302
=> Knife - Refactor to use CNEOBaseCombatWeapon, use sprint animation when sprinting

mp/src/game/client/vgui_centerstringpanel.cpp
* Fixes: https://github.com/NeotokyoRebuild/neo/issues/318
* Uses `MVP` AKA `xscale`
=> Center text use NT font

mp/game/neo/scripts/HudLayout.res, mp/src/game/client/neo/ui/neo_hud_childelement.cpp, mp/src/game/client/neo/ui/neo_hud_childelement.h, mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_compass.h, mp/src/game/client/neo/ui/neo_hud_elements.cpp
* Styling closer to OG:NT, rounded corners, faded text, compass length, and NSWE direction adjusted to OG:NT's NSWE directions
* Changed hud customisation, now can be done via `HudLayout.res` (currently OG:NT's HudLayout.res takes precedent)
* Fixes: https://github.com/NeotokyoRebuild/neo/issues/50
=> Compass HUD visual closer to OG:NT Styling + HudLayout.res customization

mp/src/game/shared/neo/neo_ghost_cap_point.cpp
For parity the distance is calculated in 3D instead of 2D, and the cap zone radius is not halved. Also, a distance less than or equal to the radius should be a cap, not just less than (this caused some annoying off by a frame issues in one of my old plugins 😅).
Fixes #269.
=> Change ghost cap distance calculation to match OG NT.

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/ui/neo_hud_elements.cpp, mp/src/game/client/neo/ui/neo_hud_elements.h, mp/src/game/client/neo/ui/neo_hud_game_event.cpp, mp/src/game/client/neo/ui/neo_hud_game_event.h
* Just let neo_hud_elements handle it like the rest of the stuff there
=> Fix exit crash around m_pGameEvent in gHud situation

mp/src/game/client/c_baseviewmodel.cpp, mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp, mp/src/game/client/view.cpp, mp/src/game/client/viewrender.cpp
* `neo_viewmodel_fov_offset` is a new ConVar to offset NT's viewmodel and can be set
* `cl_righthand` is now available and can be set
* `r_drawviewmodel` is now available and can be set
* Fixes: https://github.com/NeotokyoRebuild/neo/issues/282
* Fix the lerp section that's no longer needed and caused viewmodel shaking.
* Might fix viewmodel going random
=> Decouple viewmodel FOV, left/right toggle, draw toggle, fix viewmodel

CONTRIBUTING.md
Need to specify the dir to execute the file, at least for some terminals.
=> Fix docs command typo

mp/game/neo/scripts/HudLayout.res
The HudLayout.res wasn't updated for the asset change, causing HudMenu to have empty texts which caused the attacker info to look like nothing.
=> Fix missing HudLayout.res defines (HudMenu/HudRadio) - Fixes attacker info missing

mp/src/game/client/game_controls/SpectatorGUI.cpp, mp/src/game/client/game_controls/spectatorgui.h
* Changed from static variable to class's member variable
* Reset pointer if new scheme changed
* Also checked to make sure the score still goes up with team wins switching back and forth resolutions
* Tested on Windows + Linux, loopback + dedicated
* Fixes: https://github.com/NeotokyoRebuild/neo/issues/333
=> Fix SpectatorGUI memory corruption crash

mp/src/game/server/subs.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/neo/weapons/weapon_ghost.h, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h, mp/src/game/shared/neo/weapons/weapon_neobaseweapon.h
Fix #330 
Previously, we were overriding `SUB_Remove` for NT guns as a hack to prevent them from disappearing mid-round. This fix re-enables the correct `SUB_Remove` behaviour, and instead handles the deferred removals at the `SetPickupTouch` override, based on `mp_weaponstay` cvar's boolean value - with the exception of the ghost never being deleted from the world, regardless of the cvar's value.
We're defaulting to the more sensible `mp_weaponstay 1` behaviour to keep dropped guns in the world over parity, but the original NT behaviour can be restored by toggling this cvar to 0 instead.
=> Fix SUB_Remove deferred thinks

mp/src/game/shared/neo/neo_gamerules.cpp
* Projectiles = grenades, so smokes and frags
* fixes #289
=> Grenades shouldn't collide with players

README.md
It was thought that the menu seems broken with SourceMod, but really, it's just that `neo` has to be added to SourceMod's "supports ShowMenu" whitelist, then the menu will work just fine.
- fixes #154
=> Document SourceMod require ShowMenu whitelist for plugins to show menus

mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp, mp/src/game/client/hl2mp/clientmode_hl2mpnormal.h, mp/src/game/shared/neo/neo_predicted_viewmodel.cpp, mp/src/game/shared/neo/neo_predicted_viewmodel.h
* Seems to be the prediction system colliding it, so instead if out prediction and keep a record of the variables.
* It's kind of based on C_BasePlayer::GetFOV if-ing out prediction system. Although the start-end-time based can be kept.
* This also refactor the percentage usage to use clamp + lerp instead of basically doing the same thing as that.
* Make sure it doesn't affect loopback negatively
* Contrary to the original issue, it's replicated on both Windows + Linux
* fixes #284
* EDIT 1: Original reporter @xedmain confirmed on the fix
=> Fix buggy viewmodel ADS change transition on dedicated servers

mp/src/game/client/c_baseplayer.cpp, mp/src/game/client/c_baseplayer.h, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/neo/neo_client.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/player.cpp
Fix #336 
If spectating a player who has died, and it's been `>=DEATH_ANIMATION_TIME` since their death, look up the next valid target and switch to them.
---
Also sneaking in a `bot_next_team` server cvar, because it was useful for testing this. Set `bot_next_team` to a team index to force the next bot created by `bot_add` to join that specific team. Default value is `-1`, which instead makes the bot join the player team with less players. There's also `-2`, which makes bot join a player team completely at random. Anecdotally, this actually fixes a parity issue with bots - before this change, they were joining player teams completely randomly, but OG NT bots follow the `-1` value behaviour (which is the default now).
---
This PR duplicates some of the base `CBasePlayer` methods for …
=> Fix dead player observing & bot team join logic parity

mp/game/neo/scripts/HudLayout.res, mp/src/game/client/neo/ui/neo_hud_ammo.cpp, mp/src/game/client/neo/ui/neo_hud_ammo.h, mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_compass.h, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h
* Both ammo and health-aux huds had a hack which forces hud_reloadscheme to be called on initialization. However this has visibly caused an issue with the MOTD which in Valve's code resets the data and look a bit odd. This also enforced reload on all huds which is unnecessary.
* The proper way to load those HudLayout.res settings is instead to have those inherit EditablePanel which most importantly provides a method `LoadControlSettings` to properly load those settings instead.
* This also refactor the font applying to ApplySchemeSettings
* Minor edit in HudLayout.res chat box is intentional otherwise there's a permanent background with using this EditablePanel change.
* fixes #367
* What to change around:
* Change/add around values in: `scripts/HudLayout.res`. Minimal example to …
=> Replace hud_reloadscheme hack with EditablePanel + LoadControlSettings, indirectly fixes MOTD title + layout

mp/src/game/client/neo/game_controls/neo_classmenu.cpp, mp/src/game/client/neo/game_controls/neo_classmenu.h, mp/src/game/client/neo/game_controls/neo_loadoutmenu.cpp, mp/src/game/client/neo/game_controls/neo_loadoutmenu.h, mp/src/game/client/neo/game_controls/neo_teammenu.cpp, mp/src/game/client/neo/game_controls/neo_teammenu.h
* Affected teammenu and classmenu, loadoutmenu didn't seemed to, but also edited it just for consistency
* Reproducable with Alt-F4, although that's the default keybind for closing the window on Windows + major DEs on Linux. But using non-default keybind/other DE/WM easily reproduce it.
* fixes #371
=> Return mouse back to camera on closing VGUI dialog

mp/src/game/client/clientmode_shared.h, mp/src/game/client/game_controls/vguitextwindow.cpp, mp/src/game/client/game_controls/vguitextwindow.h, mp/src/game/server/neo/neo_client.cpp
This is a complementary PR for #366 and provides client-side control for MOTD rendering.
It also defaults the MOTD to text-only mode, so we're not by default vulnerable to attacks against the HTML renderer, and adds client side control of dismissed MOTD unloading.
Changes:
* Add `cl_disablehtmlmotd` value `2` for completely disabling the MOTD client side.
* Set default of `cl_disablehtmlmotd` to `1` instead of `0`.
* Add `cl_motd_unload_on_dismissal` which allows clients to override a `sv_motd_unload_on_dismissal 0` to force the unload.
* Set default of `sv_motd_unload_on_dismissal ` to `1` instead of `0`.
- related #366
=> Client side MOTD control

mp/src/game/client/c_baseplayer.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/player.cpp
* 8s -> fade 2s stays -> 2s unfade
* Effect local client/player after death 1st tick only
* Death goes to death cam, first person by the head ragdoll
* Some stuff to figure out when to force unfade and un-deathcam
* fixes #143
=> Fadeout after death + first person head ragdoll death cam

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.h, mp/src/game/shared/neo/neo_gamerules.h
* Instead of keeping the state of the player's team and relying on the team event callback to change it, since we're already taking the player's team on draw, just do it by draw instead. This means we won't need to hold an extra state and reduce mismatch errors.
* This also fixes/deals with how the HUD is presented to the spectator, now all players and all health shown to the spectator
* Also a fix on cursor getting stuck when hitting this issue
* This changes some variables naming from friendly/enemy to left/right due to assuming spectator's view of those HUD now. Although not all as that'll increase the PR diff.
* Refactor `DrawEnemy/DrawFriend` into a more generic `DrawPlayer`. Now able to handle if a spectator seeing the HUD.
- fixes #387
=> Fix round state HUD player's team mismatch, and allow spectator "team" to see all healthbars

mp/src/game/client/c_baseplayer.cpp, mp/src/game/shared/baseplayer_shared.cpp, mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
1st person spectator now have crosshair/scoped crosshair, and viewmodel ADS offset when the player its spectating is doing ADS.
- fixes #393
- related #390
=> Fix 1st person spectator not seeing crosshair and viewmodel offset on aim

mp/src/game/client/viewpostprocess.cpp
Disable any HDR effects whilst rendering vision modes to avoid visual interference.
Simplest way to test this is:
* Verify you have HDR enabled in game graphics options first
* Join an HDR-enabled level (link below if you have none)
* Spawn as support
* Spawn some bots with `bot_add`
* Turn on thermal vision, see if the bots get a bloomy effect surrounding their outlines. If not, all is well.
For now, here's a simple HDR enabled test map: [hdr_test.zip](https://github.com/user-attachments/files/15972956/hdr_test.zip)
=> Disable HDR while using vision mode

mp/src/game/client/neo/c_neo_player.cpp
It's possible to get in a state where the panel will cause the cursor to be stuck being not usable in 1st person viewing mode and not much to be done about it aside from restarting. This just resets the panel states, and it's at the section where the previously when the HUD panels was managed it was reset, but now it's all via gHUD, it wasn't reset properly.
- fixes #411
=> Fix cursor stuck after disconnect while in menu then reconnect

mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/ui/neo_hud_ammo.cpp, mp/src/game/client/neo/ui/neo_hud_childelement.cpp, mp/src/game/client/neo/ui/neo_hud_childelement.h, mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.cpp
* This is a **partial** fix PR not full as other places/PRs will be done to eventually piece up to fix HUDs eventually
* The hud names are all wrong due to macro trip-ups, they're now renamed to the actual one
* During client-side spawning, reset the timer to 0 and slightly tweak the conditionals so it works properly on next map again.
* #414 will be marked as related not fixed as this is a partial PR
- related #414
=> Partial fix HUD - fix timer and fix hud name

.github/ISSUE_TEMPLATE/bug_report.yml
rephrased some stuff and changed the label used for reports to an original one.
- fixes #
- related #
=> Update the bug report template

mp/game/neo/scripts/HudLayout.res, mp/src/game/client/neo/ui/neo_hud_ammo.cpp, mp/src/game/client/neo/ui/neo_hud_ammo.h, mp/src/game/client/neo/ui/neo_hud_childelement.cpp, mp/src/game/client/neo/ui/neo_hud_childelement.h, mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_compass.h, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h, mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.h
* Instead of `int` of `_r _g _b _a`, it's now all `Color` which is more convenient to edit and use
* Added other variables also to the `HudLayout.res` to make them visible to player
* Hud BG Color from "116 116 116 178" to "100 100 100 178" closer to OG:NT but not gonna try to do the whole lot as that'll take a while to compare. Doesn't even seem to be the same color visual between OG:NT and NT;RE overall or can't match.
* `neo_round_state` -> `NRoundState`
* Compass add `box_color`
- fixes #459
=> Refactor HUD scheme color variables from 4 ints to Color

mp/src/game/client/CMakeLists.txt, mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp, mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp, mp/src/game/client/neo/ui/neo_hud_friendly_marker.h, mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_marker.h, mp/src/game/server/neo/neo_player.cpp
* Remove old large text CTargetID
* Introduce distance and HP for friendly markers, shown depending on local vs target player's state
* Position now set to eye's z position, close to OG:NT
* fixes #427
* fixes #428
* fixes #429
=> Friendly markers - Remove CTargetID, dist/HP in friendly marker, pos

mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
* Fix potential nullptr dereference of `pOwner`.
* The `flScale` statement is removed entirely because it was not used for anything.
* Refactor deeply nested if statements.
* Refactor `dynamic_cast` of `C_NEOBaseCombatWeapon*` to `static_cast` for release, because all our guns are `C_NEOBaseCombatWeapon*` now.
* The `cl_neo_decoupled_vm_fov_lerp_scale` cvar is removed as unused.
- fixes #413
=> Fix crash to desktop

mp/src/game/server/hl2mp/hl2mp_player.cpp
Remove jitter when crouch walking and when crouch walking in a tight space
- fixes #478
=> Crouch Jitter

CONTRIBUTING.md
Update `CONTRIBUTING.md` CMake debug guide to include necessary flag for game to boot. (It does warn the developer on first attempt, but to save time it should be included in the documentation.)
=> Add missing arg in cmake debugging guide

mp/src/game/client/neo/ui/neo_scoreboard.cpp
Fixes some minor scoreboard issues.
The "Spectator" title was left in the wrong column after making avatars optional. It's now moved to the far left.
I thought it was annoying to see "BOT" for the SourceTV/autorecorder thing so in spectators we show empty string instead.
- fixes #446
=> Scoreboard spectator section fixes

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/weapons/weapon_grenade.cpp, mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
* Grenade used to be treated like other weapons where it get blocked when sprinting, this just gives an exemption for grenades/throwables to allow prime+throw on sprint.
* Regarding secondary throw, this is also allowed on sprint also.
* Secondary throw also fixed to make it hold rather than instant throw
* Make sure shoot and aim behavior for other weapons isn't affected/kept prevented on sprint
- fixes #456
=> Allow grenade (frag/smoke) prime+throw on sprint + fix secondary hold

mp/game/neo/scripts/weapon_aa13.txt, mp/game/neo/scripts/weapon_supa7.txt, mp/src/game/shared/neo/weapons/weapon_supa7.cpp
* Supa7 OGNT firerate is 0.8 (measured using host_timescale 0.1, 8s), not 0.875 which the script stated before
* Fix not using script's firerate
* Fix right-side CS-style icons showing up by just setting it like other weapons (this includes AA13)
- fixes #422
- fixes #440
=> Fix Supa7 firerate and right-side icon showing (Supa7 + AA13)

mp/src/game/client/menu.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/basecombatcharacter.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_player_shared.cpp, mp/src/game/shared/neo/neo_player_shared.h
* Instead of single float health variable, it's now accumlated quite like how `CBaseCombatCharacter::OnTakeDamage_Alive` does it
* Minor refactor to utilize the AttackersTotals struct more
* Fix accumlator not being reset in spawn
* Fix menu timeout being restricted to 5s max, just removed the usage of the global timeout
* Attacker info menu timeout increased to 60s
* fixes #309
=> Int+acc attacker dmg tracking, spawn reset accumlator, fix menu timeout

mp/src/game/client/clientmode_shared.cpp, mp/src/game/client/in_main.cpp
* Default configuration uses aim rather than attack2 for RMB so use that
* Also, add +specnextplayer and +specprevplayer for additional key to use instead of +attack/+aim if player wants to. If +attack/+aim keys are binded to non-mouse keys, +specnext/prevplayer can override that.
* However, these won't be in the settings menu as that configures the keys exclusively. So it'll be up to the player to use the command to keybind instead.
* fixes #434
=> Spectator - Use aim, not attack2 for next, add specnext/prevplayer

mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/weapons/weapon_ghost.cpp, mp/src/game/shared/neo/weapons/weapon_ghost.h
* On dying player ghost drop: Just use a "proper" function to drop weapons
* On disconnected/kicked player ghost drop: Use teleport/workaround so it doesn't fall through
* Ghost spawning: Give it gravity so it doesn't just stays there on given spawn origin
* fixes #423
* fixes #433
=> Fix dying + disconnect causing Ghost/weps to noclip fall, fix ghost spawn frozen in air

mp/src/game/client/vgui_centerstringpanel.cpp
* Probably to due with how it create/destroy this class
* Basically the font should be large and aliased. Before it was only one or the other.
* fixes #505
=> Center Text - Fix size and alias setting not being applied properly

mp/src/game/shared/gamemovement.cpp
Video of original problem
Uploading Recording 2024-07-06 165938.mp4…
Since player collision hull does not rotate with the entity, changing the hull min and max y offset when leaning does not have the intended effect here. Instead causes players to get stuck when beginning a lean on a staircase in certain directions
I think #152 was opened as a result of this problem, don't see any camera jitter when walking up stairs now
- fixes #152
=> Player stuck when leaning

mp/src/game/client/neo/ui/neo_hud_ammo.cpp, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
Observers (spectator/dead players) don't need to see the Health-Therm-AUX and Ammo HUDs.
- Linux GCC Distro Native Arch GCC 14
* fixes #508
=> Always hide HTA/ammo hud if observer

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/neo/neo_ghost_cap_point.cpp
* Before, the round end state HUD was trigger to any player that's by the capzone
* Instead, it should jsut be left to the gamerule which will provide the similar round end state HUD anyway
* This also turns off the visibility of ghost-related HUDs post round in the cap point, ghost beacons, and ghost marker
* Refactor to remove unnecessary variable usages
* fixes #513
=> Ghost - Cap point round end state HUD fix, HUD visibiliy post round

mp/src/game/client/neo/c_neo_player.cpp
* **NOTE: For reviewers, also checked the "related" PRs under "Linked Issues" to make sure they're not affected negatively also**
* `C_NEO_Player::Spawn` is called not only for the local client's player, but also for other player (bot or actual) when they're in the local client's PVS
* If it's called, then only update the VGUIs if it's either local player wasn't set (so it's initially just spawned in) or matches the set local player's pointer.
* fixes #510
* related #479
* related #439
* related #412
=> Fix team chooser menu popup when other player in PVS

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
* Removed the restriction on preventing ADS while weapon changing
* There doesn't seem to be an auto switch or it causing issues requiring the restriction
* static_cast the usage of GetActiveWeapon since it's all NT weapons now
* fixes #356
=> Allow ADS while changing weapons + static_cast GetActiveWeapon

mp/game/neo/scripts/HudLayout.res, mp/src/game/client/neo/ui/neo_hud_ammo.cpp, mp/src/game/client/neo/ui/neo_hud_ammo.h, mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_compass.h, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp, mp/src/game/client/neo/ui/neo_hud_health_thermoptic_aux.h, mp/src/game/client/neo/ui/neo_hud_round_state.h
Used a custom map with a totally black wall to test hud colours, think these are the original. Didn't touch the compass and round status text colour. Compass text in the original has a fade effect that needs to be implemented still, and round status element needs to be readable so left as is. Technically health sprint aux bar outlines should be drawn outside the bar itself instead of on top of the bars, so the outlines are brighter than they should be when next to actual bar. Can fix if this really bugs someone.
- fixes #455
=> Original HUD colours

mp/src/game/client/cdll_client_int.cpp, mp/src/game/server/gameinterface.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_version.cpp, mp/src/game/shared/neo/neo_version.h
* Server now just prints neo_version on startup
* Server and client long git hashes are now matched up on startup to check build integrity. If they don't, the client cannot connect unless they have matching git hashes.
* Server convar `neo_sv_build_integrity_check` to enable/disable this integrity check feature. Enabled by default.
* Server convar `neo_sv_build_integrity_check_allow_debug` to enable/disable integrity checking for debug clients. Disabled by default for release builds, enabled by default for debug builds.
* A warning message will indicate if a client bypassed the checking
* Debug bypass is determined by the first byte's final bit of (8-bits) char. 1 = debug build, 0 = release build.
* String matching will first mask out that char so even if …
=> Client vs server build integrity check + server startup print neo_version info

mp/src/game/client/hud_basechat.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_player_shared.h
Adds colon to name search, changes JINRAI and NSF colours to match original. When searching for name of sender in chat message, the search string now has a colon appended to the end. This stops the senders name from being found too early in the tags that are prepended to the message before the sender's name (*DEAD*, [Jinrai], [NSF]) being incorrectly detected as the sender's name, making chat messages be coloured in incorrectly. This is not guaranteed to always work if we add clan tags which can have colons in them, or locations of sender on the map which can also have a colon in them.
Also changes chat format slightly to match plugin parity
- fixes #436
- fixes #298
- fixes #297
=> Chat colour fix, chat format fix, retrieval zone colour fix

mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_version.cpp, mp/src/game/shared/neo/neo_version_info.h
* It can no longer use sizeof(GIT_LONGHASH) as that turned from an array into a pointer now so it returns 8 instead of ~40
=> Fix client integrity due to neo_version_info.h change

mp/game/neo/scripts/HudAnimations.txt, mp/src/game/client/CMakeLists.txt, mp/src/game/client/hl2/hud_damageindicator.cpp, mp/src/game/client/neo/ui/neo_hud_damage_indicator.cpp, mp/src/game/shared/multiplay_gamerules.cpp
Correct hud damage indicators. Haven't checked more exotic damage types like getting hit by a car or plasma gun or poison. Original red colour in the 2013 sdk seemed a bit too red, the red defined in the default burn damage overlay with an initial opacity of 25 seems very close to the original. One second for the opacity to linearly decay to 0 seems correct from the recordings I've taken also.
- fixes #528
- fixes #119
=> Correct damage indicators

mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
* Implement mirror team damage during a set duration after round starts post-freeze
* Victim is also have immunity during the duration if enabled
* Implement kick based on team damage, this is accumulated per match 
* New cvars
* neo_sv_mirror_teamdamage_multiplier - Default: 2, 0 to disable
* neo_sv_mirror_teamdamage_duration - Default: 7, 0 for the entire round
* neo_sv_mirror_teamdamage_immunity - Default: 1, 0 for no immunity from team damage
* neo_sv_teamdamage_kick - Default 0, 1 to eanble kick based on team damages per match
* neo_sv_teamdamage_kick_hp - Default 600 - Threshold to kick HP team damages per match
* neo_sv_teamdamage_kick_kills - Default 6 - Threshold to kick team kills per match
* fixes #220
=> Mirror team damage, Kick on team kill + damage accumulated threshold

mp/src/game/server/hl2/hl2_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/server/player.cpp
* Just a quick ifndef out the device that starts/ends the drain
* Also override `CanBreatheUnderwater` so it doesn't depends on AUX = 0 to drown, just being in water long enough just drowns now
* NOTE: Might want to really separate "NT aux" from "suit power" in the future, but this is good enough for now
* fixes #529
* fixes #530
=> Don't drain AUX in underwater, don't tie drowning to AUX in underwater

mp/src/game/server/neo/neo_player.cpp
Replace weapon_switch with ClientCommand
- fixes #569
=> Fix initial player tposing

mp/src/game/client/CMakeLists.txt, mp/src/game/client/cdll_client_int.cpp, mp/src/game/client/neo/neo_fixup_glshaders.cpp, mp/src/game/client/neo/neo_fixup_glshaders.h
This is a hack around the vision mode shaders sporadically breaking on Linux builds.
It seems that for whatever reason, the shader state cached at the `glshaders.cfg` file somehow leads to the corruption upon successive runs of the game, and write-protecting the file offers a simple way to avoid that breakage.
Ideally, we should figure out  what's really going wrong here at the shader system and/or precaching level, but this should suffice for avoiding the bug.
~~I opted to implement this as a CMakeLists step rather than submit the glshaders file itself, because to my understanding git does not version control the "read-only" file permissions required to keep the game from modifying the file.~~
edit: The hack is now done at runtime, because doing it in the CMake scripts won't carry over …
=> Workaround for Linux shaders breakage

mp/game/neo/resource/ClientScheme.res, mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_ui.cpp, mp/src/game/client/neo/ui/neo_ui.h
* Now the normal font is green mountain for readability
* This is applied to main sections and popups
* Neuropol2 is kept for title, tabs, main menu steam/news, and bottom sections
* Refactored the naming of the fonts enums
* fixes #591
=> NeoUI - Change normal font to from neuropol2 to green mountain

mp/src/game/shared/neo/weapons/weapon_supa7.cpp
As Agiel pointed out, Supa7's ItemPostFrame was Finishing the reload before a slug could be loaded if there was no primary ammo in the gun
- fixes #576
=> Supa7 use Slugs with no primary ammo

mp/src/game/client/neo/game_controls/neo_classmenu.h, mp/src/game/client/neo/game_controls/neo_loadoutmenu.h, mp/src/game/client/neo/game_controls/neo_teammenu.h
Based on a crash dump. We can't safely call this virtual method from the constructor, so converting it to non-virtual. As we aren't overriding a function, and we're not being overridden, this shouldn't have any effect to other systems.
- Linux GCC Distro Native [Mint 21.3 Cinnamon, gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0]
None
=> Fix crash at Neo menu constructors

mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
Add some safety checks before using these pointers, because this area had segfaulted for v8.0-prealpha (Linux):
Trace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
warning: Section `.reg-xstate/4255' in core file too small.
#0  0xdd621cc3 in CNEOHud_GhostMarker::DrawNeoHudElement (this=0x15ad4800) at /home/runner/work/neo/neo/mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp:177
[Current thread is 1 (Thread 0xf5be2000 (LWP 4255))]
(gdb) frame 1
#1  0xdd766c0f in vgui::Panel::PaintTraverse (this=0x15ad4848, repaint=<optimized out>, allowForce=true) at /home/runner/work/neo/neo/mp/src/vgui2/vgui_controls/Panel.cpp:1224
(gdb) frame 1
#1  0xdd766c0f in vgui::Panel::PaintTraverse (this=0x15ad4848, repaint=<optimized out>, allowForce=true) at …
```
=> Add extra guards against segfault

mp/src/game/server/neo/neo_detpack.cpp, mp/src/game/server/neo/neo_grenade.cpp, mp/src/game/server/neo/neo_smokegrenade.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
* If it's like EX: 1v3 alives, the 3-person team is playing the ghost then the single-alive player decides to suicide, this will reward the ghost playing/winning team a rank up since the suicide player tries to prevent a ghost cap.
* Checks for: suicide, suicide by environment, disconnects, and posthumous teamkill (suicide/disconnects)
* New convar:
* neo_sv_suicide_prevent_cap_punish - Default: 1 to enable this feature
* fixes #215
=> Award XPs to oppositing team if player tries to prevent ghost cap

mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_ui.cpp, mp/src/game/client/neo/ui/neo_ui.h
* Basically go back to settings instead, in which settings have a "Restore" button anyway
* fixes #590
=> Settings changed popup - Replace discard with cancel

README.md, mp/src/game/shared/neo/neo_mount_original.h
Make the `-neopath` launch argument work on Linux.
- Linux GCC Distro Native [Mint 21.3 Cinnamon, gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0]
* Launch the game with `-neopath "/your/custom/path/here"` Steam advanced launch parameter
* See that it doesn't use the parameter.
* The parameter is used correctly.
* Main menu game console reports: `Client using custom -neopath: /your/custom/path/here`
* Game correctly errors for invalid `-neopath` values
None
=> Fix -neopath for Linux

mp/src/game/client/cdll_client_int.cpp, mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_root_settings.cpp
* Enforce con_enable 1 to fix console toggle issue
* Instead always enforce the "legacy" toggleconsole, because internally it requires con_enable to be set anyway, although the legacy menu toggles this.
* Basically means the support for legacy menu on this is an unsupported thing anyway
* Write the command file on save
* Fix attempts to write empty keys
* Unbind duplicate key
* fixes #586
=> Enforce con_enable 1 and multiple fixes for keybind handling

mp/src/game/server/neo/neo_player.cpp
When spawning in a round, the primary weapon you choose does not automatically activate like it should. This breaks both weapon selections for players, but seems to affect bots too. The player is left in the pistol animation without any weapon selected, and pressing `+attack` does nothing in this state.
This is a regression from d209d44b; the parent commit 51a1ef42 does not observe this behaviour.
I propose we revert #570 (commit d209d44b), because it was intended to fix #569 but doesn't, so it's only introducing new bugs currently.
* Join a server
* Join a team
* Choose a class
* Choose a loadout
* Your chosen loadout is activated as you spawn in.
* Bots will also spawn with their primary weapon active.
* You spawn empty-handed, until you manually select your weapon.
* Bots also spawn …
=> Revert "replace weapon_switch with ClientCommand (#570)"

mp/src/game/server/hl2/hl2_player.cpp
=> Recon aux regen rate halved when sprinting

mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_root_settings.cpp, mp/src/game/client/neo/ui/neo_root_settings.h
* To workaround console not working for non-BACKQUOTE key layouts, allow the rebinding of the console to any key the user wants. This is also beneficial for people who also just want to put console to a separate key.
* Non-BACKQUOTE keys however requires the root menu to handle the key and toggleconsole itself, whereas BACKQUOTE key will always envoke. The root menu will handle it if it's active without a console opened. Otherwise the engine will envoke it even for non-BACKQUOTE itself if you're in-game without the root menu opened or the console is already opened.
* Nevra, who uses FR AZERTY confirmed this works well for him
* fixes #620
=> NeoUI - Console toggle key rebind, intended for non-` key layouts

mp/src/game/client/hud_crosshair.cpp
Cleaner scope. Every pixel that had any transparency has been left untouched, a black ring placed around the center and a surface blur used to bleed into the surrounding colour used to block  parts of the screen not covered by the texture.
This PR only had the changes to the outer block colour to match the outer colour of the scope in https://github.com/NeotokyoRebuild/neoAssets/pull/2
If you approve please also approve https://github.com/NeotokyoRebuild/neoAssets/pull/2
=> Cleaner scope

mp/src/game/shared/neo/weapons/weapon_detpack.cpp, mp/src/game/shared/neo/weapons/weapon_grenade.cpp, mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
give viewoffset so origin always appears above ground when dropped when performing a cansee calculation
- fixes #233
=> Throwables origin clipping into ground workaround

mp/src/game/shared/neo/weapons/weapon_grenade.cpp, mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
=> Grenade throw source position closer to center of screen

mp/src/game/shared/neo/neo_gamerules.cpp
3 mintues 15 seconds long rounds, 15 seconds of which are during the pre-round freeze
- fixes #627
=> Correct default round timings

mp/src/game/server/neo/neo_client.cpp
check if player death time is the default death time when respawning, only applies during the first three seconds of the server
- fixes #644
=> Allow player respawning during the first three seconds of the server

mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp
Currently, any resolution exceeding 1440 pixels horizontally will result in the uplink icon clipping below the compass rose on the HUD. This aims to mitigate this issue for up to 4K (my max resolution).
4K (3840x2160) before changes
4K (3840x2160) after changes
I have also tested swapping resolutions and watching the `vgui_drawtree` highlight to see if it stays consistent. Not sure if there are any other scenarios I might need to try out but it seems fine.
=> Adjust Uplink element for larger resolutions

mp/src/game/shared/gamemovement.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/util_shared.cpp, mp/src/game/shared/util_shared.h
Fix the collision detection which went too far. It should only be dealing with movement
=> Fix collision (knife, bullet, blood) by limiting NT collide check to only movement

mp/src/game/client/CMakeLists.txt, mp/src/game/client/cdll_client_int.cpp, mp/src/game/client/clientmode_shared.cpp, mp/src/game/client/neo/ui/neo_loading.cpp, mp/src/game/client/neo/ui/neo_loading.h, mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_root.h, mp/src/game/client/neo/ui/neo_ui.cpp, mp/src/game/client/neo/ui/neo_ui.h, mp/src/public/vgui_controls/Frame.h
* Re-route the old VGUI text/progress into NeoUI
* Loading vs disconnect states by title locale index
* Single-progress bar as 2nd one not used
* Preload map name if known (serverlist + new game)
* `NeoUI::LabelWrap` for a wrapped version of a label
* `NeoUI::Progress` a read-only progress bar
* No mouse input since it doesn't work properly/workarounds doesn't work well
- fixes #603
=> NeoUI - Custom loading screen, wrapped text

mp/src/game/server/neo/neo_detpack.cpp, mp/src/public/const.h
Increase main sound cut-off point, use correct explosion sound for detpack
Sounds in the original game can be heard from up to 10k hu away. This is 10 times larger than the current sound cutoff point.
Currently the detpack also uses an explosion sound with a special parameter that switches to a weaker distant explosion in the sounds right channel when the character is a set distance away from the explosion. The original detpack's explosion sound doesn't change much even out to 10k hu.
https://github.com/user-attachments/assets/64dacc92-6c44-4c82-915e-d6a361849581
- fixes #584
=> Detpack correct sounds

mp/src/game/client/clientmode_shared.cpp
Sometimes it can crash on exit due to a direct delete. Even then it kind of doesnt even matter much if delete or not since the lifetime of this is practically once whole session and OS cleans up on exit anyway.
=> Fix possible crash on exit - NeoLoading

mp/src/game/client/neo/ui/neo_ui.cpp, mp/src/game/client/neo/ui/neo_ui.h
* Current scrollable sections that's immediately noticable:
* Settings -> Keys
* Create server/game -> Map list selector
* There might be others like player lists, but they all have the same behavior/style anyway
* Handles mouse drag/click and paint just right-side of defined panel
* fixes #666
=> NeoUI - Add scrollbar to scrollable sections

mp/src/game/server/neo/neo_player.cpp
Set movetype to walk only when spawning as jinrai or nsf
- fixes  #640
=> Stop camera from falling when initially selecting a team

mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.h, mp/src/game/server/client.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
* A (not enabled by default) ready up mechanic that will only start a game if the players ready match the defined threshold (default to 5v5)
* Allows to override the limit if desired, although for either scenarios will still require equal amount of players between Jinrai and NSF
* New native player commands to set/unset ready state, configure override limit, and check players not ready
* The override limit will reset to false when players drops below threshold
* Automatic intermission can be turned off with the ready-up feature on
* HUD round state fixed to just directly take the const wchar_t strings and therefore no need for ANSI->WCHAR conversions
* Make sure round wins and XPs are resetting on non-intermission/idle/warmup to ready
* Player commands
* !ready - For the player to signal …
=> Add ready up mechanic to start a match, allow non-auto-intermission

mp/src/game/shared/gamemovement.cpp, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/util_shared.cpp, mp/src/game/shared/util_shared.h
* Revert bb49e49ce31cc7b65198232410c111bfa023dfc4.
* Revert 82df07f62ec019b9d1fe67fa002b88eafc4baa31.
* It doesn't work properly with actual players (only bots/LAN dedicated), and instead caused a "soft" blocking?
* Not gonna bother anymore, it's mixed up with the tracing stuff. If team-based blocking couldn't be done properly like this then might as well go back to the previous no-blocking code which worked fine for quite a long time anyway
* fixes #704
=> Revert "team based blocking and options"

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/weapons/weapon_detpack.h, mp/src/game/shared/neo/weapons/weapon_grenade.cpp, mp/src/game/shared/neo/weapons/weapon_grenade.h, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h, mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp, mp/src/game/shared/neo/weapons/weapon_smokegrenade.h
Fix problems with throwable items like grenades.
This PR disables priming throwables with the `+attack2`/"alt fire" button, as that seemed to be happening by mistake.
This also removes the experimental underhanding/lobbing of grenades feature. This was never really properly implemented, and was just remnants from tests years ago. It's not parity, and if we wanted this kind of system in the future, it should probably go through a proper design doc process to be added.
Finally, this fixes the inability to throw grenades/throwables whilst sprinting - parity behaviour is to allow throwing of nades regardless of sprint state.
- Linux GCC Distro Native [Mint 21.3 + GCC 11.4.0]
- Fix #708 
- Fix #713
=> Fix grenade bugs

mp/src/game/client/game_controls/SpectatorGUI.cpp, mp/src/game/client/game_controls/spectatorgui.h
Update player label on think
- fixes #137
=> Communicate player label in real time

mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/neo_gamerules.cpp
* Fixes the issue where you do not spawn after being killed by a player
* Fixes where you cannot switch class while you're allowed to switch weapons
* Also add a menu on spawning in to easily switch class
* fixes #712
=> Backport DM's fixes + spawn menu to master

mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp
* 60s was too long, turned down to 10s
* Add the ability to dismiss and not have the info for the rest of the match
* fixes #717
=> Damage/killer info duration 60s->10s + Dismiss forever

mp/src/game/client/clientmode_shared.cpp
Still getting crash here (user after free on dangling pointer?). Just don't handle it. It's also called on exit so it's unnecessary to even cleanup here anyway.
=> Do not delete g_pNeoLoading ourselves, probably already done by engine

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp
Will fix the issue where after death your own view model remains visible in the spot where you died. No clue what caused it initially, this is a workaround I guess.
(Edit) Use Rain's solution instead
- fixes #720
=> Hide own view model on death

mp/src/game/server/baseentity.h, mp/src/game/server/neo/neo_detpack.cpp, mp/src/game/server/neo/neo_smokegrenade.cpp, mp/src/game/shared/neo/weapons/weapon_ghost.h
The `SUB_Remove` think function pointer was made virtual in aae9c8053a3b52c87289d006c6d44ea6cb3d9a1f as a workaround to fix weapons disappearing mid-round. This was later properly addressed in 429f83fd379345e48190cb3e4425acf9495f7a44, making the virtual declaration redundant. Hence I'm removing the virtual declaration for simplicity, and to avoid the needless vtable indirection overhead.
- Linux GCC Distro Native [Mint 21.3 + GCC 11.4.0]
=> Make SUB_Remove non-virtual

mp/src/game/client/CMakeLists.txt, mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp, mp/src/game/client/neo/ui/neo_hud_game_event.cpp, mp/src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/client/neo/ui/neo_hud_round_state.h, mp/src/game/client/neo/ui/neo_scoreboard.cpp, mp/src/game/client/neo/ui/neo_ui.cpp, mp/src/game/server/CMakeLists.txt, mp/src/game/server/neo/neo_dm_spawn.cpp, mp/src/game/server/neo/neo_dm_spawn.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/hl2mp/hl2mp_gamerules.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h, mp/src/game/shared/neo/neo_misc.cpp, mp/src/game/shared/neo/neo_misc.h, mp/src/game/shared/neo/neo_player_shared.cpp, mp/src/game/shared/neo/neo_player_shared.h
* **TODO: Weapon restriction? (Separate PR)**
* Deathmatch spawning
* Use info_player_deathmatch entity if possible
* Otherwise can just use the separate file (dmspawn)
* Vector of spawns checked if it been filled at the current fill, spawned in starting from a given random int to the next available spawn
* Deathmatch gameplay
* Either to maximum XP or time runs out
* If tying at max XP or post time out, it'll end when there's a single highest XP winner
* UI
* HUD round state adjusted for DM
* Scoreboard adjusted for DM, no Jinrai/NSF coloring
* ConVars
* neo_sv_dmspawn_useent - Default 0, override to use map's deathmatch spawn entity over the dmspawn loc file
* neo_sv_dm_max_class_dur - Default 5s, maximum duration you're allowed to pick a class post-spawning in
* neo_dm_round_timelimit …
=> Deathmatch gamemode

mp/src/game/shared/neo/weapons/weapon_knife.cpp, mp/src/game/shared/neo/weapons/weapon_milso.cpp, mp/src/game/shared/neo/weapons/weapon_tachi.cpp, mp/src/public/bspflags.h
https://github.com/NeotokyoRebuild/neo/discussions/625
- fixes #565
=> Tachi and Milso can no longer shoot underwater, water now protects from bullets

mp/src/game/shared/neo/neo_gamerules.cpp
* Basically a change moved the round number increment after the spawning causing it to differ between spawning in live verses in freezetime
=> Fix mis-match between round start and current spawning

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp
DM/TDM can have multiple players seen at "one round" which means > 100hp/scores. Still keep the cap mostly for sanity checking on non-DM/TDM gametypes.
=> Do not cap DM/TDM attackers scores to 100

mp/src/game/server/neo/neo_player.cpp
* Server-side convar: neo_sv_warmup_godmode - 0 by default, if 1, everyone takes no damage at all, regardless of bullets, fall, or nades during idle or warmup state
* fixes #206
=> Warmup Godmode

mp/src/game/shared/neo/weapons/weapon_knife.cpp, mp/src/game/shared/neo/weapons/weapon_knife.h
Fix a problem where the knife swing could be incorrectly triggered once, using the `+attack2` input.
This is a supplementary fix to #708 since I forgot to address the knife stuff in the earlier PR #714 that closed the issue.
We had some buggy scaffolding in place for supporting a speculative future secondary attack feature for the knife, but in the spirit of YAGNI I've decided to delete it for now to simplify the code.
See #708 (only the knife case is applicable here, grenades should be already fixed).
- Linux GCC Distro Native [Mint 21.3 + GCC 11.4.0]
- fixes #708 
- related #714
=> Fix knife incorrect initial secondary attack

mp/src/game/client/c_baseanimating.cpp, mp/src/game/client/c_basecombatcharacter.cpp, mp/src/game/client/clientmode_shared.cpp, mp/src/game/client/glow_outline_effect.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/public/model_types.h
Re-overrides the material used to draw player glow for every new player drawn, disabled enabling of xray when dead spectating teammates, moves the toggle off of xray vision when changing teams to clientmodeshared
- fixes #702
=> Spectator xray toggled off on spawn, fixes to how outline is drawn

mp/src/game/client/CMakeLists.txt, mp/src/game/client/c_playerresource.cpp, mp/src/game/client/cdll_client_int.cpp, mp/src/game/client/clientmode_shared.cpp, mp/src/game/client/hud_basechat.cpp, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/client/neo/ui/neo_hud_round_state.cpp, mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/client/neo/ui/neo_root_settings.cpp, mp/src/game/client/neo/ui/neo_root_settings.h, mp/src/game/client/neo/ui/neo_scoreboard.cpp, mp/src/game/server/gameinterface.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_player_shared.h
* No avatar
* No names (only generic ones)
* **Won't do:** Custom names
* fixes #150
=> Streamer mode

mp/src/game/client/neo/ui/neo_hud_compass.cpp, mp/src/game/client/neo/ui/neo_hud_compass.h, mp/src/game/client/neo/ui/neo_root_settings.cpp, mp/src/game/client/neo/ui/neo_root_settings.h
* In meters, the distance between the player and solid wall
* Skybox and >= 1000m will return "---m" to show infinity value
* Only shown in ADS
* ConVars:
* neo_cl_hud_rangefinder_enabled - 1 as default, Toggle enable/disable
* neo_cl_hud_rangefinder_pos_frac_[x/y] - 0.55 as default, position in fraction in screen width/height
* Added to settings > General to toggle rangefinder
* fixes #761
=> Rangefinder HUD

mp/src/game/client/neo/ui/neo_hud_compass.cpp
* It got removed in #520?
- related #455
=> Restore compass fade code

mp/src/game/client/neo/c_neo_player.cpp
Returns the IFF indicators above friendly players when player was previously using xray in spectator mode. Also fixes a problem where xray button had to be pressed twice to enable xray in spectator mode if person was using xray previously before respawning.
- fixes #783
=> IFF fix when previously using xray

README.md
target/link were confused. the command as it was would create a link from linux32 TO sdk32 (or if it's an existing folder, as it would be here, confusedly create a broken sdk32 link inside of linux32.)
=> Correct improper symlink command order

mp/src/game/client/vgui_fpspanel.cpp
Upon further investigation it seems that cl_showfps is the only command affected, even though many others use labels in the neoui element
- fixes #814
=> add min and max to cl_showfps

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/c_neo_player.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/basecombatweapon_shared.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
Weapons that weren't active weren't getting data updates and so ShadowCastType() wasn't being run for them. This pr switches how we control whether shadows are drawn for weapons specifically to instead use the effect EF_NOSHADOW. I've tested bots toggling cloak on and off manually, bots running out of cloak, bots dropping weapons while cloaked, bots dying while cloaked and the shadow behavior for all of these seems correct.
One situation I can think of that I haven't tested where this might break would be a cloaked player who enabled cloak while not in pvs running into view of the player.
- fixes #831
=> Use EF_NOSHADOW to control weapon shadow state

mp/src/game/client/CMakeLists.txt, mp/src/game/client/neo/material_proxies/neo_matproxy_teamnum.cpp
Material proxy for getting the team of the entity the material is attached to.
If this proxy were used on a material for any of the jinrai player skins, it would return 2 (given its actually being used on a jinrai player)
It will give an output from resultVar like other proxies.
0 = Unassigned
1 = Spectator
2 = Jinrai
3 = NSF
=> Material proxy for getting team number

mp/src/game/server/neo/neo_grenade.cpp, mp/src/game/server/neo/neo_grenade.h
Standing near a grenade explosion no longer triggers screnshake. This is not an issue with detpack.
- fixes #839
=> GH-839 Move grenade detonation without screenshake

mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h
Input for the player entity that sets the player model as determined by the path included in the input parameters
It will also disable gibbing on that player until they respawn so their corpse is consistent with the model change
Assets PR: https://github.com/NeotokyoRebuild/neoAssets/pull/17
- related #819
=> Input for setting custom player model

mp/src/game/client/in_main.cpp, mp/src/game/client/in_main.h, mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/client/neo/ui/neo_root_settings.cpp, mp/src/game/client/neo/ui/neo_root_settings.h, mp/src/game/server/neo/neo_player.cpp, mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
Automatic leaning. Currently using automatic leaning prevents the use of manual leaning completely.
=> Automatic leaning

mp/src/game/server/neo/neo_client.cpp, mp/src/game/server/neo/neo_player.cpp, mp/src/game/server/neo/neo_player.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
Prevents players from spawning if previously spawned during that ongoing round, and enforces the DEATH_ANIMATION_TIME in game modes with respawns enabled.
Ensures people who spawn during freeze time are frozen.
Also stops spectators from being respawned and frozen during round start.
- fixes #793
=> Fair spawn mechanics

mp/src/game/server/neo/neo_game_config.cpp, mp/src/game/server/neo/neo_game_config.h, mp/src/game/shared/neo/neo_gamerules.cpp, mp/src/game/shared/neo/neo_gamerules.h
This adds three inputs and two outputs to neo_game_config to give mappers greater control over the game, potentially to add custom win conditions or special effects.
FireTeamWin - Ends the round with the team specified in the parameter as the winner (2 = Jinrai, 3 = NSF)
FireDMPlayerWin - Ends the round in deathmatch with the activating player as the winner
FireRoundTie - Ends the round as a tie
OnRoundEnd - Fired when any team wins or ties
OnRoundStart - Fired after "- GO! GO! GO! -"
In a scenario where the winning team is ambiguious, the mapper can have an output go through two team filters to then trigger FireTeamWin. I did not check the team of the activator to deterimine the winner instead as this can be more restrictive in some scenarios
I will make an FGD entry for this filter as …
=> Add IO to neo_game_config for custom round events

mp/game/neo/scripts/HudLayout.res, mp/src/game/client/CMakeLists.txt, mp/src/game/client/neo/ui/neo_hud_hint.cpp, mp/src/game/client/neo/ui/neo_hud_hint.h
Hints, hopefully identical to how they appeared in OGNT
Includes a convar to turn them on / off
- fixes #863
=> Pre-round hints on HUD

mp/src/game/client/viewpostprocess.cpp
We disable hdr when using vision modes already, but that doesn't revert the changes to the tonemap made by hdr when it was enabled.
=> Fix vision modes on maps with colour correction and or hdr

mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
Fixes the problem commonly found in automatic weapons where two bullets are fired in the same frame. The check whether cycle time has passed in PrimaryAttack is unnecessary, we're already checking if the cycle time has passed in ItemPostFrame where we avoid doing floating point math
- fixes #835
=> Fix two bullets fired in one frame

mp/game/neo/scripts/weapon_mpn_unsilenced.txt
give mpn_unsilenced same fov and viewmodel offset as mpn
=> mpn_unsilenced fov and viewmodel offset when aiming

mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
* Add missing crouch spread modifier. In OGNT the inaccuracy decays faster while crouching, which is something I initially missed.
* Fix Jitte hip fire spread. No idea how I entered that so wrong, it was correct in my tables. Max hip spread decreased from 10 -> 7 degrees.
* Add experimental dynamic view kick toggle (_sv_neo_dynamic_viewkick_, default off). Basically this makes it so the view kick is proportional to the inaccuracy. Doesn't make much difference at inaccuracy scale 1, but is massive at lower values.
- related #107, #560
=> Spread parity errata.

mp/src/game/shared/baseplayer_shared.cpp
Different thresholds at crouching vs walking
- fixes #363
=> Footstep velocity thresholds at parity

mp/src/game/client/viewrender.cpp
Will hide screen overlays (from env_screenoverlay, r_screenoverlay, or any other means) when the player is using their vision mode
Did this because it can mess with brightness in vision modes, especially with NV where the environment is very dark.
=> Disable screen overlays when in vision modes

mp/src/game/client/neo/c_neo_player.cpp, mp/src/game/server/neo/neo_player.cpp
Not sure if when using toggle lean we should force players to toggle on leaning again after being in mid-air or after sprinting. I guess we could leave the functionality as is in this pr and then any players who want sprinting to un-lean could bind pressing the sprint key to releasing both lean keys? Idk discuss.
=> No leaning when sprinting

mp/src/game/client/hud_crosshair.cpp, mp/src/game/client/hud_crosshair.h
https://github.com/user-attachments/assets/76020803-4f4e-4261-bbb6-ecdcb21e2868
- fixes #868
=> IFF Crosshair

mp/src/game/shared/basecombatweapon_shared.cpp, mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
3 Seconds of delay after running out of ammunition before automatic reload kicks in, unless you dryfire specifically by pressing the attack key down (instead of holding the attack key down) after you've already run out of ammunition. Also fixes to the srs clicking when holding down the attack key to prevent the bolt from being cycled automatically after running out of ammunition (thought I already fixed this but I guess no?)
- fixes #567
=> Dryfire behaviour parity and zr68l sprinting viewmodel fix

mp/src/game/client/neo/ui/neo_root.cpp, mp/src/game/shared/neo/neo_version_info.cpp.in, mp/src/game/shared/neo/neo_version_info.h
=> Fix incorrect version info string display in main menu

mp/src/game/client/hud_pdump.cpp, mp/src/game/server/hl2/hl2_player.cpp, mp/src/game/server/player.cpp
If had primary holstered, primary will no longer fall through the ground, and ghost will not be stuck to hands when picking up with use key. Also fixed cl_pdump because the command was not taking up the entire screen and a lot of the information was getting cut off
=> Fix picking up the ghost with use key

mp/src/game/server/neo/neo_grenade.cpp, mp/src/game/server/neo/neo_smokegrenade.cpp
Gave the smoke and frag grenade the same treatment as the detpack since that seems to be parity behaviour. There is some code in the sdk grenades to disable friendly collisions of grenade projectiles for the first x seconds of life, might want to use that if we start adding new utility which should interact with players like impact grenades and whatnot
=> Grenades don't collide with players

mp/src/game/client/c_baseplayer.cpp, mp/src/game/shared/baseplayer_shared.cpp, mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
Now client side setting always applies
-fixes #917
=> viewmodel leaning in spectator 2

mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
when using xray while spectating a support in thermals, their viewmodel glows white. No longer
=> Disable thermal vision view model override when using xray

src/game/server/neo/neo_detpack.cpp, src/game/shared/neo/weapons/weapon_detpack.cpp, src/game/shared/neo/weapons/weapon_detpack.h, src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
Detpack projectile does not inherit owner velocity, has settled check checks velocity and if groundentity is set, fixes to the viewmodel when sprinting
- fixes #906
=> Detpack Fixes

game/neo/resource/ClientScheme.res, game/neo/scripts/HudLayout.res, src/game/client/CMakeLists.txt, src/game/client/neo/c_neo_message.cpp, src/game/client/neo/c_neo_message.h, src/game/client/neo/ui/neo_hud_message.cpp, src/game/client/neo/ui/neo_hud_message.h, src/game/server/CMakeLists.txt, src/game/server/neo/neo_message.cpp, src/game/server/neo/neo_message.h
This is an entity that draws localised text in a box styled after the original hints. Optionally plays a sound when triggered
To use the entity use the ShowMessage input with the localisation key as the parameter with a # before it
In the localised text use \n to start a new line
[neoAssets PR](https://github.com/NeotokyoRebuild/neoAssets/pull/25)
=> Tutorial - Hints

src/game/server/nav_ladder.cpp, src/game/server/nav_ladder.h
Fixes the error that shows up for maps with func_ladder but actually holds the information it's supposed to this time
- fixes #893
=> info_ladder 2

src/game/client/c_baseplayer.h, src/game/server/player.h, src/game/shared/baseplayer_shared.cpp, src/game/shared/baseviewmodel_shared.cpp, src/game/shared/neo/neo_predicted_viewmodel_muzzleflash.cpp, src/game/shared/neo/neo_predicted_viewmodel_muzzleflash.h
Ideally the updateViewModelMuzzleFlash function should belong to the CNEOViewModelMuzzleFlash, but when doing it that way changing the muzzle flash skin doesn't seem to have an effect
- fixes #571
=> Correct muzzle flash when server switches weapons

.github/workflows/cibuild.yml, src/CMakeLists.txt, src/game/client/neo/neo_fixup_glshaders.cpp, src/mathlib/CMakeLists.txt
Use `registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest` docker container for Linux builds.
Sadly, it's impossible to use `container` with `matrix`, so the build job is now split into `linux-build` and `windows-build`.
`gamedata-gen` URL will be updated after merge of this [PR](https://github.com/NeotokyoRebuild/gamedata-gen/pull/1).
- Windows MSVC VS2022 (GitHub actions)
- Linux GCC 10 Sniper 3.0 (GitHub actions)
- Linux GCC Arch Linux Native (g++ (GCC) 14.2.1 20250207)
- fixes #966
=> Use sniper docker container

src/game/shared/neo/neo_predicted_viewmodel.cpp
angle of 35 passes the same values to the bone controller as seen in og using cl_pdump <playerIndex> while leaning in either direction
=> Parity third person leaning angle

src/game/shared/basecombatweapon_shared.cpp
fix ghost speech on ghost drop after f5a07d6b
- fixes #979
=> ghost speech after drop since f5a07d6b

src/game/client/neo/ui/neo_hud_ammo.cpp, src/game/shared/neo/weapons/weapon_detpack.cpp
player velocity but halved seems about right, detpack detonates too soon, halving instead of thirding seems about right, also don't draw some ui elements in the weapon hud element when using a detpack
- fixes #989
- fixes #991
=> Detpack velocity again and detpack detonation time

src/game/server/neo/neo_player.cpp, src/game/shared/neo/neo_predicted_viewmodel.cpp, src/game/shared/neo/weapons/weapon_grenade.cpp, src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, src/game/shared/neo/weapons/weapon_smokegrenade.cpp
In the case of the grenade angular impulses we were previously using the values Rain calculated in-game. Using cl_pdump the angular velocity of the grenade projectile is 0 in all directions so I'm guessing Rain observed the angular position of the projectiles over time and calculated them that way. The reason these are probably wrong I'm guessing is because the order in which the position in the x y and z direction is displayed is not the same as the order in which the impulse in the three directions is passed in in the grenade projectile creation function. Here are the values for a grenade projectile in the original
Once the base sdk angular impulse values are substituted in in rebuild, the angular position of the projectiles looks a lot more similar (notice the zeroed out middle …
=> muzzle light, toc flash and grenade angular impulse

src/game/server/hl2mp/hl2mp_player.cpp, src/game/server/neo/neo_player.cpp
Move ragdoll creation from hl2mp_player::Event_Killed to neo_player::Event_Killed, move call to baseclass Event_Killed to after our custom weapon dropping code is ran, back to where it was originally
- fixes #1028
=> [Regression Fix] Active weapons falling through floor on death

src/game/server/neo/neo_smokegrenade.cpp
New Assets in -------> https://github.com/NeotokyoRebuild/neoAssets/pull/32 <-------
Reduces the opacity of the smoke overlay when walking near a smokegrenade smoke, and reduced the number of particles used to render the smoke grenade effect, allowing for more smoke grenades to be active at the same time by 2.5x.
- fixes #1030
- fixes #1031
=> original number of smoke layers

src/game/shared/neo/neo_gamerules.cpp
nullptr dereference on pScorer causing the crash
* fixes #1045
=> Fix nullptr dereference causing crash on environmental deaths

src/game/server/bmodels.cpp
Hamfisted fix to prevent looping move sounds from playing when the entity isn't moving
=> Func_rotating moving sound fix

src/game/server/neo/neo_player.cpp, src/game/shared/neo/neo_gamerules.cpp
* Short pause is now 1 min
* `sv_neo_comp 1` fixed to turn on pausing
* Fixed chat .help print limit when having both lobby and pause enabled
* fixes #1070
=> Short pause 1min, sv_neo_comp do pause cvar, print fix

src/game/client/neo/ui/neo_hud_deathnotice.cpp
Before:
After:
- Linux GCC Native [Arch, g++ (GCC) 14.2.1 20250207]
=> Fix broken unicode text in killfeed

src/game/server/effects.cpp
Just stops the error from popping up in maps that use it.
The compiler should just delete the entity when it's done with it, but it doesn't, so
=> func_detail_blocker support

src/game/client/neo/ui/neo_hud_round_state.cpp, src/game/client/neo/ui/neo_hud_round_state.h, src/game/server/neo/neo_client.cpp, src/game/server/neo/neo_player.cpp, src/game/shared/neo/neo_gamerules.cpp, src/game/shared/neo/neo_gamerules.h
* A round status that goes between when all teams are fully ready and before the first round goes live
* Also beep sound (clientside) during countdown
* fixes #1022
=> Ready up - Add countdown stage before the match starts

src/game/shared/neo/weapons/weapon_grenade.cpp, src/game/shared/neo/weapons/weapon_smokegrenade.cpp, src/game/shared/neo/weapons/weapon_supa7.cpp
Small tweaks to the supa7 and grenades to make the viewmodel animations smoother.
For the supa7, this fixes the problem where tapping the reload button quickly right after firing causes the weapon to return to the idle viewmodel animation for a split second during the reload.
Here is a video showing the problem
https://github.com/user-attachments/assets/a186665f-2dfc-4f3a-9012-351a3bb96598
For the grenades, this fixes the problem where tapping the attack key to throw a grenade causes the grenade throw animation to be played in the middle of the pin pull animation. difficult to replicate, I had the most success replicating this by tapping the attack key quickly towards the end of the ACT_VM_DRAW animation
Here is a video where the second throw has this animation discrepancy …
=> Supa7 viewmodel reset during reload, and grenade viewmodel throw animation during pin pull animation fixes

src/game/client/c_baseanimating.cpp
https://github.com/user-attachments/assets/627bee26-ebdd-4c09-a30f-62cec902a52f
=> Fix viewmodels becoming dark when standing close to and facing a wall

src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h
See issue for description
- fixes #1074
=> add shader detail very high option

src/game/client/neo/ui/neo_hud_deathnotice.cpp, src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h
=> Option to disable extended killfeed

src/game/shared/neo/neo_gamerules.cpp, src/game/shared/neo/neo_gamerules.h
Spawn the ghost on odd-indexed rounds at the same place as the previous round in competitive
- fixes #204
=> Ghost Spawn Bias

src/game/server/neo/neo_game_config.cpp, src/game/shared/gamerules.cpp, src/game/shared/neo/neo_player_spawnpoint.cpp, src/game/shared/neo/neo_player_spawnpoint.h
Title. If a player spawned at a spawn within 128 units of another spawn it would make the other spawn not valid, causing players to spawn inside other players
It might be better to have a more robust way of checking if a player has been spawned at a point but IDK.
- fixes #1099
=> Fix players spawning inside eachother, spawnpoint features, small code cleanup

src/game/shared/neo/neo_predicted_viewmodel.cpp, src/game/shared/neo/neo_predicted_viewmodel.h
When standing right up against a wall and peeking around a corner, moving the aim point to the left of the line running perpendicular to the wall that you're standing against will cause the player to begin un-leaning immediately due to the collision with the wall, throwing the aim off. This PR allows the aim to be moved further to the left before the character begins unleaning.
This pr also makes unleaning when hitting an obstacle instant, to prevent the camera from clipping through the wall. It's still possible to an extend, may have to increase the trace distance but then not factor that value into the return percentage in freeroomforlean
- fixes #
- related #
=> More lenient lean around corners, harsher unlean when running into a wall

src/CMakeLists.txt
Enable the FetchContent output so developer can see the downloading process, otherwise it looks like CMake configure phase is frozen for a minute (depends on download speed) due to the size of neoAssets.
Example output:
```[cmake] [1/9] Creating directories for 'neo_assets-populate'
[cmake] [1/9] Performing download step (git clone) for 'neo_assets-populate'
[cmake] Cloning into 'neo_assets-src'...
[cmake] remote: Enumerating objects: 1212, done.        
[cmake] remote: Counting objects:   0% (1/1212)        
[cmake] remote: Counting objects:   1% (13/1212)        
...
[cmake] remote: Counting objects: 100% (1212/1212)        
[cmake] remote: Counting objects: 100% (1212/1212), done.        
[cmake] remote: Compressing objects:   0% (1/655)        
...
[cmake] remote: Compressing objects: …
```
=> Show FetchContent output by default

src/game/client/view.h, src/game/shared/neo/neo_predicted_viewmodel.cpp, src/game/shared/neo/neo_predicted_viewmodel.h
undo parts of 1b05d97b that return camera faster during unlean due to collision, reduce camera near z plane to fix camera clipping instead
Before:
After:
=> Camera clipping at high fov

src/game/client/c_baseanimating.cpp
Before:
After:
- Linux GCC Native [Arch, g++ (GCC) 15.1.1 20250425]
- fixes #1126 
- related #1085
=> Fix black viewmodel bug

src/game/client/neo/c_neo_player.cpp, src/game/client/neo/c_neo_player.h, src/game/server/neo/neo_player.cpp, src/game/server/player.cpp
Moves calls to setspectatetarget server side to avoid mismatch between client and server spectatetarget
(NOTE) This does not fix the viewmodels not showing up sometimes on bots when bot_attack is set to 1
- fixes #1058
- fixes #929
=> Spectate viewmodel missing in some situations

src/game/client/neo/ui/neo_hud_ammo.cpp, src/game/client/neo/ui/neo_hud_friendly_marker.cpp, src/game/client/neo/ui/neo_hud_round_state.cpp
Before:
After (never mind the wrong Linux font):
Related PR: #1081
- Linux GCC Native [Arch, g++ (GCC) 15.1.1 20250425]
=> Fix broken unicode text in player squad list

src/game/server/hl2mp/hl2mp_player.cpp, src/game/server/neo/neo_player.cpp, src/game/server/player.cpp
Reverts the snowfall fix that made weapons given to players spawn at their eyes  #671, and instead skip the line of sight check if the weapon a player is bumping into has the same origin as the player
- fixes #1114
=> Bump Weapon Skip LOS check

src/game/client/c_baseanimating.cpp, src/game/client/neo/c_neo_npc_dummy.cpp, src/game/client/neo/c_neo_player.cpp, src/game/client/neo/c_neo_player.h, src/game/client/viewpostprocess.cpp, src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
Use spectate target vision mode in first person only. Should also fix seeing other vision modes prematurely.
- related #937
- related #939
=> Use spectate target vision mode in first person only

src/game/server/neo/neo_player.cpp, src/game/server/triggers.cpp
`trigger_serverragdoll` can be used to make the ragdolls of players simulate serverside to prevent them from falling through dynamic objects. This could previously only be used for NPCs
=> trigger_serverragdoll applies to players

src/CMakeLists.txt, src/game/client/CMakeLists.txt
Remove obsolete CMake options that were just a port from VPC build.
Move client-only dedicated server-related compile definitions to client so it won't affect the server build.
- Linux GCC Native [Arch, g++ (GCC) 15.1.1 20250425]
=> Remove obsolete CMake options, speed up dedicated server build on Linux

src/game/client/hud_crosshair.cpp, src/game/client/hud_crosshair.h, src/game/client/neo/ui/neo_hud_crosshair.cpp, src/game/client/neo/ui/neo_hud_crosshair.h, src/game/client/neo/ui/neo_root.cpp, src/game/client/neo/ui/neo_root.h, src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h, src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
* All crosshair convars now converge into just `cl_neo_crosshair`
* String based serialization instead of file
* Copy/paste crosshair import/export functionality
- Linux GCC Distro Native Gentoo/GCC 14.2.1
* fixes #1180
=> Crosshair - Change to single string convar + serialization

src/game/client/clientmode_shared.cpp, src/game/client/glow_outline_effect.cpp, src/materialsystem/stdshaders/include/neo_haloaddoutline_ps20b.inc, src/materialsystem/stdshaders/neo_haloaddoutline_ps2x.fxc
[NeoAssets PR](https://github.com/NeotokyoRebuild/neoAssets/pull/53)
Switched to a full frame buffer for the outline, for a more accurate player outline Made a copy of the haloaddoutline_ps20b shader, with the only difference being the width of the shader now being configurable from the material and/or in code via convar. Also made the opacity of the fill shader a convar too, this way both can be configured and disabled with values of 0
=> Configurable Xray

src/game/shared/neo/weapons/weapon_supa7.cpp, src/game/shared/neo/weapons/weapon_supa7.h
In the original pressing the attack key cancels a reload if one is in progress, the weapon is only fired if the attack key is still held after the reload is stopped.
In the original beginning a reload from a completely empty clip will cue a shotgun rack that will play at the end of the reload sequence. This can be skipped by pressing the attack key, the rack will then try to play the next time the weapon is reloaded even though there could still be ammunition in the clip and the weapon was just fired. This PR adds this mechanic with a slight adjustment so this shotgun rack cannot be skipped 
This PR also makes the reloading of the shotgun quicker. The original does not let the full reload animation play and instead loads a fresh shell every ~0.5 seconds
Also gives the firing of the …
=> Remove delayed fire from the supa7, adds more weapon racking like in OG (plus a little extra), faster reloading of supa7, attack priority over reload

game/neo/scripts/HudLayout.res
Turns out these proportional_ypos / width / etc variables don't change when the resolution is changed while the game is running unless they have an entry in HudLayout.res
=> Round win/tie center hud element not resizing on resolution change fix

src/game/client/c_te_playerdecal.cpp, src/game/client/cdll_client_int.cpp, src/game/server/player.cpp
* Allow impulse 201 (spray) in freezetime
* Prevent impulse 201 if the client disabled spray
* Delete custom downloaded sprays on both startup and shutdown
* Both startup and shutdown mostly to workaround filesystem API bug trying to recognize some of the files
* Test on `*.dat` sprays deletion on Windows (rainyan tested)
* fixes #1205
=> Spray handling improvements - Freezetime, disabled spray, cleanups

src/game/client/neo/ui/neo_hud_ghost_beacons.cpp, src/game/client/neo/ui/neo_hud_ghost_beacons.h, src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp, src/game/client/neo/ui/neo_hud_ghost_cap_point.h, src/game/client/neo/ui/neo_hud_ghost_marker.cpp, src/game/client/neo/ui/neo_hud_ghost_marker.h, src/game/client/neo/ui/neo_hud_worldpos_marker.cpp
Size of elements now depends solely on convar settings for those hud elements (and resolution for the ghost beacons when scaling with distance is enabled I guess)
- fixes #787
=> World pos hud elements ignore texture size

src/game/client/cdll_client_int.cpp, src/game/client/hud_crosshair.cpp, src/game/client/hud_crosshair.h, src/game/client/neo/c_neo_player.cpp, src/game/client/neo/c_neo_player.h, src/game/client/neo/ui/neo_hud_crosshair.cpp, src/game/client/neo/ui/neo_hud_crosshair.h, src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h, src/game/server/neo/neo_player.cpp, src/game/server/neo/neo_player.h, src/game/shared/neo/neo_gamerules.cpp, src/game/shared/neo/neo_player_shared.h
* Since the change to string-based serialization is applied, it's now more straightforward to implement networked crosshair
* The networking is similar to how it's done for `neo_name` and `neo_clantag` as it's just strings passed around
* `cl_neo_crosshair_network` 0 = disable viewing other players crosshair, 1 = show other players crosshair
* "Other players crosshair" meaning when you're spectating the other person in 1st person while they ADS
* NeoUI settings - Slight alterations, added set to default button but also crosshair no longer part of the full-on reset button, so like the volume setting won't reset on full-on settings reset
* NeoUI settings - Added toggle for viewing networked crosshair
* NeoUI settings - Export/Import(/Default) buttons no longer restricted to only custom
* …
=> Networked crosshair

src/game/shared/multiplay_gamerules.cpp
Add the `neo_restart_this` cvar for parity.
This cvar differs from `mp_restartgame` in that the latter will give a countdown, whereas `neo_restart_this` is instant.
As a side note, the cvar `mp_restartgame_immediate` seen below is `CTeamplayRoundBasedRules` related, which is not part of our gamerules inheritance chain, and its logic is not quite right, so that's why I'm rolling my own callback for the cvar.
=> Add neo_restart_this support

src/game/client/neo/c_neo_player.cpp, src/game/client/neo/game_controls/neo_classmenu.cpp, src/game/client/neo/game_controls/neo_classmenu.h, src/game/client/neo/game_controls/neo_teammenu.cpp
the previous fix to class selection showing up in spectate plus disable cancel button when unassigned, set picture in class selection menu on team join event
for reference this is how the team selection menu looks in the original when unassigned
=> correct class team on class selection menu, disable cancel button when unassigned

src/game/client/cdll_client_int.cpp, src/game/client/clientmode_shared.cpp, src/game/client/neo/ui/neo_root.cpp, src/game/client/neo/ui/neo_root.h, src/game/client/vgui_int.cpp
This reverts commit aa58c4a25c76798a82c3b0816a8187af558f8152. Because there's issues with mouse focus screwing with the other dialogs, just reverting this should fix that one and instead the `-tools` option will load up the legacy main menu instead.
=> Revert NeoUI mouse handling change, -tools loads up legacy main menu instead

src/game/client/mp3player.cpp, src/game/client/neo/ui/neo_root.cpp
Fix #1235, #1236
We still have the problem #1237  here that the user can't assign multiple keybinds for the same command, because the latest bind will always take precedence. But that's outside the scope of this PR.
- fixes: #1235 
- fixes: #1236 
- related: #1237 
- possibly(?) related: #1166
=> Fix UI bind bugs

src/game/client/neo/ui/neo_root.cpp, src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h, src/game/client/neo/ui/neo_scoreboard.cpp, src/game/client/neo/ui/neo_ui.cpp, src/game/client/neo/ui/neo_ui.h, src/game/shared/neo/neo_gamerules.cpp, src/game/shared/neo/neo_player_shared.cpp, src/game/shared/neo/neo_player_shared.h
* Add right-click menu for NeoUI, only used by TextEdit for clipboard functionality
* Clipboard actions envoked both by keybind and right-click menu
* Add selection support for TextEdit
* Cursor set on any position other than final + paste in-between texts
* Text selection with shift modifier + HOME/END/LEFT/RIGHT
* Prev/next word with ctrl modifier + LEFT/RIGHT (vgui ctrl modifier behavior)
* Password TextEdit toggle now a flag in function rather than context bool variable
* TODO later?: Multi-lined text editor, read-only mode, slider's text editor. Those can be done later as this PR is already long.
* Refactored NeoUI mouse handling, added ability to override foreground/text color
* Mark create server password field as password if streamer mode is on
- Linux GCC Distro Native Gentoo/GCC …
=> NeoUI - Clipboard + selection + free-cursor for TextEdit

src/game/server/neo/neo_player.cpp
Because the sounds are emitted from the player, the player is preserved and the trigger is not so it never tells the player to stop
They're also really loud and annoying so I made them stop when the player dies also
- fixes #1272
=> Fix leech sounds playing when they shouldnt

src/game/client/neo/ui/neo_hud_ammo.cpp
Fix buffer overrun bugs in the ammo UI causing a crash to desktop.
Sadly I don't have steps to reproduce the crash, but this is based on a crash memory dump from my own match.
=> Fix client crash

src/game/client/smoke_fog_overlay.cpp
The value of g_SmokeFogOverlayAlpha is calculated somewhere in the engine and prevents the xray overlay from working, g_SmokeFogOverlayThermalOverride isn't enough to fix it since we don't have access to that code so have to set the value of g_SmokeFogOverlayAlpha to 0 to get it working again.
To test this start a match with bots, spawn as a support, throw a smoke, kill yourself, go into free roam spectate mode and fly into the smoke, enable xray, and look towards the bots.
Will still draw the smoke fog overlay in the case where we are on a team and mp_forcecamera is set to anything other than OBS_ALLOW_ALL
=> Don't draw smoke fog overlay when xraying

src/game/client/c_baseanimating.cpp, src/game/client/c_soundscape.cpp, src/game/client/clientshadowmgr.cpp, src/game/client/neo/ui/neo_scoreboard.cpp, src/game/client/smoke_fog_overlay.h, src/game/server/NextBot/Player/NextBotPlayerBody.cpp, src/game/server/NextBot/Player/NextBotPlayerBody.h, src/game/server/baseflex.cpp, src/game/server/genericactor.cpp, src/game/server/neo/bot/neo_bot.cpp, src/game/server/neo/bot/neo_bot.h, src/game/server/neo/bot/neo_bot_body.cpp, src/game/server/neo/bot/neo_bot_body.h, src/game/shared/neo/neo_predicted_viewmodel_muzzleflash.cpp, src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp, src/public/datamap.h, src/public/vgui_controls/PropertySheet.h
* Cleanup compiler warnings that showsup in GCC
* neo_bot_body override the `VEC_` usage methods and fix macro redef warning for NextBodyPlayerBody and make then use `SDK_VEC_` prefix macros instead
* fixes #1312
=> Cleanup GCC compiler warnings + `VEC_` neo_bot_body overrides

.gitignore
Linux have case-sensitive filesystem, it needs exact match
=> gitignore chapterbackgrounds.txt

src/game/client/neo/ui/neo_root_settings.cpp, src/game/client/neo/ui/neo_root_settings.h
exposes the zoom_sensitivity_ratio convar.
negative values invert controls when aimed in ( can only be set via console/config file )
a value of 0 removes the scaling of mouse sensitivity with fov
a value less than 1 scales down sensitivity when aimed in
a value greater than 1 scales up sensitivity when aimed in ( values greater than 10 only via console/config file )
=> Zoom sensitivity ratio in settings

src/game/client/neo/ui/neo_loading.cpp
When creating a listen server, the host_map convar gets updated almost immediately with the name of the map we're loading into, if connecting to a dedicated server however this only happens when we're almost finished loading. 
Since the whole reason we're doing this is to stop the loading screen from showing up when loading into a background map, and we should only really be loading into a background map on a listen server, we can assume that if host_map doesn't return a value, that we are connecting to a dedicated server at which point we should be showing a loading screen. In reality we still see the loading screen for a couple frames but that's much better than the current behavior.
As a side note, engine->GetLevelName() will return the map on a dedicated server when connecting quicker …
=> Show loading screen if unsure what map we're loading into

src/game/client/CMakeLists.txt, src/game/server/CMakeLists.txt, src/game/server/neo/bot/behavior/neo_bot_attack.cpp, src/game/server/neo/bot/behavior/neo_bot_behavior.cpp, src/game/server/neo/bot/behavior/neo_bot_seek_and_destroy.cpp, src/game/server/neo/bot/behavior/neo_bot_tactical_monitor.cpp, src/game/server/neo/bot/neo_bot.cpp, src/game/server/neo/bot/neo_bot.h, src/game/server/neo/bot/neo_bot_vision.cpp, src/game/server/neo/bot/neo_bot_vision.h, src/game/shared/baseentity_shared.cpp, src/game/shared/decals.h, src/game/shared/neo/neo_penetration_resistance.cpp, src/game/shared/neo/neo_penetration_resistance.h
* Bots should now be able to shoot through glass if not using a shotgun
* If using a shotgun, try to change to a weapon that can utilize the glass if possible
* Change back to a shotgun if not behind glass?
* Tested/check if it doesn't straight up shoot through any penetrable like wallhack ability, non-glass penetrable only shoot through if it's recently seen enemy
* Enemy player that can shoot towards the ghoster behind penetrable should be able to try shooting at it
* Test/check for non-penetrable glass (tarmac non-penetrable vs oilstain penetrable)
* Slight scale between weapon penetration on when the bots will attempt to do penetration, so like SRS will do longer distance than SRM.
* Limited wallbang at ghoster ability to hard + expert bots
* …
=> Bots - Shoot through glass + penetrateables

src/game/client/neo/ui/neo_hud_deathnotice.cpp, src/game/client/neo/ui/neo_hud_round_state.cpp, src/game/client/neo/ui/neo_scoreboard.cpp
This is to prevent readability issues on the scoreboard.
Much of the information provided by these two HUD elements is on the scoreboard, and the scoreboard can be quickly turned on/off as it has to be held open
=> Hide squad list and killfeed if the scoreboard is showing

src/game/client/c_baseanimating.cpp, src/game/client/c_baseentity.h, src/game/client/hl2mp/c_hl2mp_player.cpp, src/game/client/hl2mp/c_hl2mp_player.h, src/game/client/proxyplayer.cpp, src/game/client/ragdoll.cpp, src/game/client/ragdoll.h
There is an issue on master thats kinda difficult to replicate, but sometimes you will notice some ragdolls will freeze while still being slightly highlighted in motion vision, with the velocity no longer updated as the ragdoll goes to sleep. This PR sets the value of the ragdoll velocity to 0 when a ragdoll goes to sleep
=> zero out ragdoll velocity if ragdoll is settled, refactor ragdoll velocity stuff out of c_baseanimating into cragdoll

src/game/client/neo/ui/neo_hud_killer_damage_info.cpp, src/game/server/neo/neo_player.cpp
`GetClassname` instead of `GetDebugName` as mappers can set the targetname to pretty much anything
=> Use class name for killer info, unify name for all neo_npc_targetsystem

src/game/client/neo/ui/neo_hud_round_state.cpp, src/game/client/neo/ui/neo_scoreboard.cpp, src/game/client/neo/ui/neo_scoreboard.h
Playtesters expressed confusion regarding the teams icon/score swapping sides, as currently the local player's team is always left.
This can cause it to become misaligned with the scoreboard and not appear where the player expected their team's score to be
=> Option to make the round info and scoreboard HUD not swap team sides

game/neo/scripts/HudLayout.res, src/game/client/neo/ui/neo_hud_deathnotice.cpp
Fix suicide with assister display, reverse highlight and non highlight colours
- fixes #1230
=> Remove assister from suicide with assist notice, reverse highlight and non highlight colours

src/game/client/neo/ui/neo_hud_round_state.cpp, src/game/client/neo/ui/neo_hud_round_state.h
Changes made to hide the warmup text was not enough, overlap would still happen in other instances (e.g. match point)
Match status should take priority over the gamemode description
- related #1337
=> Always draw match status over gamemode description

src/game/shared/neo/weapons/weapon_ghost.cpp, src/game/shared/neo/weapons/weapon_ghost.h
Fix server crash due to dangling ptr if ghost is deleted mid-match.
- fixes #1351
=> Fix dangling gamerules ghost ptr

README.md
Fixes grammar, phrasing, and consistency issues in `README.md`.
- Corrected verb agreement (e.g., "assumes" -> "assume", "have" -> "has").  
- Replaced incorrect word forms (e.g., "sequentiality" -> "sequentially", "setup" -> "set up" when used as a verb).  
- Fixed missing/extra words (e.g., "appid based" -> "appid-based search path is an issue").  
- Standardized style (e.g., "Metamod" capitalization, "showup" -> "show up").  
- Minor polish for clarity and readability.
=> Fix README grammar and improve phrasing

src/game/client/neo/ui/neo_root.cpp, src/game/client/neo/ui/neo_root.h
* In the details section can toggle
* Right-click add/remove server favorite
* fixes #1267
=> NeoUI - Add and remove server favorites

src/game/client/clientmode_shared.cpp, src/game/client/neo/c_neo_player.cpp, src/game/client/neo/c_neo_player.h, src/game/server/baseentity.cpp, src/game/server/neo/neo_player.cpp, src/game/server/neo/neo_player.h, src/game/shared/hl2/hl2_usermessages.cpp, src/game/shared/neo/neo_gamerules.cpp, src/game/shared/neo/neo_player_shared.h
Proof of concept for taking over AFK players and bots as a spectator
- fixes https://github.com/NeotokyoRebuild/neo/issues/1254
=> Spectator ability to take over bots and AFK players

src/game/client/neo/c_neo_player.cpp, src/game/client/neo/c_neo_player.h, src/game/server/neo/neo_player.cpp, src/game/server/neo/neo_player.h, src/game/shared/gamemovement.cpp, src/game/shared/gamemovement.h, src/game/shared/neo/neo_player_shared.cpp
This is intended to replace the current hard speed cap that comes with the neo_ghost_bhopping cvar. Air friction is applied when going faster than the current max walking speed (based on class and active weapon), and scales linearly with how much faster the player is going.
The friction can be controlled with the following new cvars:
* **sv_neo_airfriction** _(Default: 0)_: The amount of air friction applied to everyone.
* **sv_neo_airfriction_objective** _(Default: 0.5)_: The amount of air friction applied to the ghost carrier, VIP and juggernaut.
* **sv_neo_airstopspeed** _(Default: 0)_: The minimum stopping speed when in the air. Doesn't seem necessary with the default friction value of 0.5, but it's added for parity with ground friction.
For testing purposes, a cheat protected cvar …
=> Introduce air friction as a replacement for the hard speed cap to prevent ghost hopping

game/neo/scripts/HudLayout.res, src/game/client/neo/ui/neo_hud_compass.cpp, src/game/client/neo/ui/neo_hud_compass.h
Implements proper text fade at the edges instead of a gradient overlay. Instead of drawing one long string, each direction label is drawn separately.
The objective now has an actual compass direction instead of using screen space.
All the customizability (in HudLayout.res);
* Position and size
* Text and background color
* Fade exponent
* Field of view
* Whether to draw separators
- fixes
- related #970
=> Compass revamp

src/game/shared/neo/weapons/weapon_grenade.cpp, src/game/shared/neo/weapons/weapon_smokegrenade.cpp
Seems like pPlayer->LocalEyeAngles() now returns (-180, 180) whereas in SDK/OGNT it used to be (0, 360). This causes the trajectory equation to fail. This rewrites it to work with the new interval.
- fixes #1384
=> Grenade trajectory parity
