NeotokyoRebuild/neo

- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
- mp/src/game/shared/shareddefs.h
Adjusted sizes of models to fit original, adjusted viewoffsets and used viewoffsets during lean viewoffset calculation
> Hull size and smooth leaning

- mp/src/game/client/in_camera.cpp
- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/shared/hl2mp/hl2mp_player_shared.cpp
- mp/src/game/shared/neo/neo_playeranimstate.cpp
- mp/src/game/shared/neo/weapons/weapon_detpack.h
> Animations networking

- mp/src/game/server/baseentity.cpp
applied fix from V952 in this github thread https://github.com/ValveSoftware/source-sdk-2013/issues/213 to fix the jittery view when walking up steep staircases
> The sticky feet / stair jitter fix

- mp/src/game/client/neo/c_neo_player.cpp
team menu doesn't get moved in front of the motd
> MOTD in front

- mp/src/game/client/hud_crosshair.cpp
Death messages no longer hidden by the marksman scope
> Death notification panel above marksman scope

- mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp
Removed tint from friendly marker ui element
> Removed tint from friendly marker ui element

- mp/src/game/shared/gamemovement.cpp
- mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
- mp/src/game/shared/shareddefs.h
adjusted viewoffsets using test map to prevent camera clipping through ceilings, offset now actually used in lean function
> More leaning viewoffset fixes

- mp/src/game/shared/neo/weapons/weapon_knife.cpp
- mp/src/game/shared/neo/weapons/weapon_knife.h
* This really just hides the knife if the player is not alive and they're not using the weapon
> Hide knife visibility when dead

- mp/src/game/client/view.cpp
> Fix CE change merge regarding zoom

- mp/src/game/server/neo/neo_player.cpp
* The initial merge seems ok, but somewhere down the line it got removed accidentally
> Fix some merge taking out cloak update lines

- mp/src/game/server/hl2mp/hl2mp_player.h
* Still using the old steam-runtimes toolchain
> override -> OVERRIDE fix for Linux compile

- mp/src/game/server/basecombatcharacter.cpp
- mp/src/game/server/hl2mp/hl2mp_player.cpp
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/server/neo/neo_player.h
- mp/src/game/shared/neo/weapons/weapon_detpack.cpp
- mp/src/game/shared/neo/weapons/weapon_detpack.h
- mp/src/game/shared/neo/weapons/weapon_grenade.cpp
- mp/src/game/shared/neo/weapons/weapon_grenade.h
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
- mp/src/game/shared/neo/weapons/weapon_pz.cpp
- mp/src/game/shared/neo/weapons/weapon_pz.h
- mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
- mp/src/game/shared/neo/weapons/weapon_smokegrenade.h
- mp/src/game/shared/neo/weapons/weapon_supa7.cpp
- mp/src/game/shared/neo/weapons/weapon_supa7.h
Moved pickup checking logic to guns
Player can pick up any utility
Nades drop correct amount
Nades refill ammo from drops
> Moved gun dropping logic to guns

- mp/src/CMakeLists.txt
- mp/src/game/client/CMakeLists.txt
- mp/src/game/server/CMakeLists.txt
- mp/src/materialsystem/stdshaders/CMakeLists.txt
* Set default optimization level to -O2 and disable two optimizations to fix vgui button issue.
* Create NEO_OUTPUT_LIBRARY_PATH directory when configuring.
> Fix vgui button issue

- mp/src/game/server/neo/neo_player.cpp
Fixes https://github.com/NeotokyoRebuild/neo/issues/301
> Prevent supports from being given a knife

- mp/src/game/server/neo/neo_player.cpp
* Fixes: https://github.com/NeotokyoRebuild/neo/issues/129
> Fix cloak sound not giving sounds server side

- mp/src/CMakeLists.txt
- mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
- mp/src/game/client/neo/ui/neo_hud_ghost_marker.h
in-code ghost marker animation
> Ghost Marker animated

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
- mp/src/game/client/neo/ui/neo_hud_round_state.h
also picture outline and combined score with center box
> Colourful healthbars

- README.md
Added instructions for hosting a dedicated NT;RE server on a Windows machine.
> Added Instructions for "Dedicated Server on Windows"

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/server/neo/neo_player.cpp
* Also made sure `neo_aim_hold 1` is not affected negatively by this change
* fixes #285 fixes #276 fixes #355
> Change ADS toggle from on-release to on-press and sprint related bug fixes

- mp/game/neo/materials/dev/motion_third.vmt
- mp/src/game/client/neo/c_neo_player.cpp
Now overrides cloak
Change material shader to ignore lighting and stop it from flickering
Still missing: 
Shader with gradient effect
Items/props having MV applied
> Motion Vision Working

- mp/src/game/shared/hl2mp/hl2mp_weapon_parse.cpp
* `Smoke Grenade` and `Frag Grenade` hits it, especially for dedicated server side + loopback
* These don't need cycle time
> Fix grenade asserts hitting in debug mode (srcds)

- mp/src/game/server/neo/neo_client.cpp
* New server side cvar `neo_sv_show_motd` to control if server wants the MOTD shown or not
* SDK2013CE change that changed from `msg` to `message`
* Always disabled for loopback, server convar toggle for dedicated
* This PR does not deal with HUD looking broken/reset, this will be done separately in a different PR as that's more for the HUDs in general than just MOTD. Issue raised to track for that: https://github.com/NeotokyoRebuild/neo/issues/367
* fixes #65 fixes #66
> Don't show MOTD by default, don't ever show for loopback

- mp/game/neo/scripts/kb_act.lst
- mp/src/game/client/in_main.cpp
- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/c_neo_player.h
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/shared/neo/neo_player_shared.cpp
- mp/src/game/shared/neo/neo_player_shared.h
- mp/src/game/shared/neo/neo_predicted_viewmodel.cpp
- mp/src/game/shared/neo/neo_predicted_viewmodel.h
* Fix `m_bInLean` not being client side predicted
* You can use `cl_pdump 1` to verify this - `m_bInLean` should no longer flash red whilst leaning
* Improve the lean lerp prediction
> Improve lean prediction

- mp/game/neo/cfg/user_default.scr
* It got replaced by keybind already
> Remove lean toggle convar in multiplayer advanced

- mp/src/game/client/fx_blood.cpp
Defaults all blood bullet impact decals to the default blood bullet impact, which is very close to the original 
- fixes #244
> Blood Impact visual closer to og

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
- mp/src/game/client/neo/ui/neo_hud_round_state.h
- mp/src/game/shared/neo/neo_player_shared.h
- mp/src/game/shared/shareddefs.h
* Off-center fixed by moving the variable settings over to `ApplySchemeSettings` (do note the diff looks a bit crap atm so view as the whole file)
* Also fix when supposed to not have visible strings it wasn't cleared, but now will explicitly clear them all properly and won't look stuck on map change
* Refactor
* Common variables like stars and class are array-based
* Refactored initialization and fetching of data
* Reduce amount of variables holding position state
* Removed `m_iYPos - 2` calculations which always comes down to 0 anyway
* Renamed, changed types, removed variable same sizes of the other one
- fixes #405
> Round state HUD - Refactor, fix res change, fix round 0 strings

- .github/workflows/issues-exporter.yml
- .github/workflows/main.yml
Add a issues exporter action
https://github.com/NeotokyoRebuild/paperwork/issues/13
- fixes # https://github.com/NeotokyoRebuild/paperwork/issues/13
- related #
> github-issues-sheets-exporter

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/server/player.cpp
* Now unleans/not leans on death
* POI mode skipped over to next/prev enum
* fixes #418
* fixes #451
> Spec fixes - Lean 3p spec fix, POI mode filtered out

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp
- mp/src/game/client/neo/ui/neo_hud_friendly_marker.h
- mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
* First person don't show ghost holder's ghost marker
* First person don't show friendly/from spec friendly marker
* Any spec don't show ghost beacon, that's only for active ghost player
- fixes #421
> Spec HUD fixes - FP no ghost holder + friendly hud, and no spec ghost beacon

- mp/game/neo/materials/vgui/hud/roundend_jinrai.vmt
- mp/game/neo/materials/vgui/hud/roundend_nsf.vmt
- mp/game/neo/materials/vgui/hud/roundend_tie.vmt
- mp/game/neo/resource/ClientScheme.res
- mp/game/neo/resource/ClientScheme_Neo.res
- mp/src/game/client/neo/ui/neo_hud_game_event.cpp
- mp/src/game/client/neo/ui/neo_hud_game_event.h
* Set graphics and fonts as non-additive so it doesn't fade on black
* Add 2px offset render behind main render
* Some bit of refactor in the class also
* fixes #472
> Round-end graphic drop shadow

- mp/src/game/shared/neo/weapons/weapon_supa7.cpp
prevent shooting when sprinting with supa
> prevent shooting when sprinting with supa

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/c_neo_player.h
* Just go from deathcam -> none, user clicks -> spec
* Will have to press LMB to start spec but now won't be shown to non-VM state
* fixes #426
> Spec fixes - Death to spectator VM fix

- mp/src/game/client/CMakeLists.txt
- mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
- mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h
- mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp
- mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h
Adds the ghost uplink hud element to the bottom of the screen, modified ghost beacons to be closer to the original
- fixes #441
- fixes #430
- fixes #89
> Ghost Uplink, ghost beacons closer to og

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
Looks a bit cleaner
* fixes #453
> Round state text remove parentheses

- mp/src/game/server/basecombatcharacter.cpp
- mp/src/game/shared/basecombatweapon_shared.cpp
- mp/src/game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.cpp
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
Prevents the drawing of neo weapons if the weapons belong to the local player and the player is in first person mode
- fixes #420
> Remove duplicate weapon view models

- mp/src/game/server/hl2mp/hl2mp_gameinterface.cpp
> SourceTV maxplayers fix

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
- mp/src/game/shared/neo/neo_player_shared.h
- mp/src/game/shared/shareddefs.h
Old Squad HUD plus some adjustments
- fixes #145
> Old Squad HUD

- mp/src/game/shared/neo/neo_ghost_cap_point.cpp
Testing this pr requires #470 to be merged in
See https://github.com/NeotokyoRebuild/neo/issues/269#issuecomment-2255877159 for explanation and map to test this pr
- fixes #269
> Ghost capzones match NT06 in size

- mp/src/game/shared/neo/weapons/weapon_ghost.h
Pick up ghost with use key
- fixes #544
> Pick up ghost with use key

- mp/game/neo/scripts/weapon_grenade.txt
- mp/game/neo/scripts/weapon_smokegrenade.txt
- mp/src/game/shared/neo/weapons/weapon_grenade.cpp
- mp/src/game/shared/neo/weapons/weapon_grenade.h
- mp/src/game/shared/neo/weapons/weapon_smokegrenade.cpp
- mp/src/game/shared/neo/weapons/weapon_smokegrenade.h
- Windows MSVC VS2022\
- fixes #535
> Grenade drawback fix

- mp/src/game/client/hl2mp/c_hl2mp_player.cpp
- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/server/hl2/hl2_player.cpp
- mp/src/game/server/neo/neo_player.cpp
> Sprinting in water, crouch sprinting, speeds touchup

- mp/src/game/server/hl2mp/hl2mp_player.cpp
Increase Supa7 Slug Damage
- fixes #575
> Supa 7 Slug Damage

- mp/game/neo/resource/ClientScheme.res
> Font at higher resolutions too bright

- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
prevent weapon sequence from being networked for neocombatweapons. World model doesn't have any and view model can only be seen by the client using the weapon, so doesn't need to be networked
- fixes #449
> weapon sequence console spam

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/shared/neo/neo_player_shared.cpp
- mp/src/game/shared/neo/neo_player_shared.h
damage inflictor can be the projectile used to kill the player, or the player that killed the player
- fixes #596
> Damage info panel correct weapon

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/c_neo_player.h
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/server/neo/neo_player.h
- mp/src/game/shared/baseentity_shared.cpp
- mp/src/game/shared/neo/neo_gamerules.cpp
Useful for gamemodes like tdm also where respawns are enabled
- fixes #287
> Weapon Selection Available 15 seconds after round is live, 25 seconds after spawning

- mp/src/game/server/neo/neo_player.cpp
No changing skin when round is live or over
- fixes #582
> Mid round skin swapping

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
reload image list on applyschemesettings
- related #639
> Reload image list in roundstate hud element when changing video settings or running hud_reloadscheme

- mp/src/game/shared/neo/neo_gamerules.cpp
- mp/src/game/shared/neo/neo_gamerules.h
- mp/src/game/shared/util_shared.cpp
* New convar: neo_sv_collision
* 0 (default) - No blocking at all
* 1 - Team-based blocking
* 2 - All players blocking
> Add team based blocking and options to turn blocking on

- mp/src/game/client/CMakeLists.txt
- mp/src/game/client/hud_crosshair.cpp
- mp/src/game/client/hud_crosshair.h
- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/ui/neo_hud_crosshair.cpp
- mp/src/game/client/neo/ui/neo_hud_crosshair.h
- mp/src/game/client/neo/ui/neo_root.cpp
- mp/src/game/client/neo/ui/neo_root.h
- mp/src/game/client/neo/ui/neo_root_settings.cpp
- mp/src/game/client/neo/ui/neo_root_settings.h
- mp/src/game/client/neo/ui/neo_ui.cpp
- mp/src/game/client/neo/ui/neo_ui.h
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
- mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
* Asset PR: https://github.com/NeotokyoRebuild/neoAssets/pull/6
* Add ability to create a custom crosshair with parameters to configure them
* Can import and export the crosshair from/to a separate serialized binary file
* Choice between the current default and "custom" crosshair at the moment
* Currently limited to using `vgui::surface` drawing primatives, so circle/rects are through those APIs at the moment
- fixes #604
> Custom crosshair - Customization + import/export file

- mp/src/game/server/neo/neo_player.cpp
When I was working on DM and realized spawning in after the first one doesn't give you loadout properly and stuck with pistol. Affects TDM in master branch.
> Fix spawning in no loadout - Effects TDM

- mp/game/neo/resource/chatscheme.res
- mp/game/neo/resource/ui/basechat.res
- mp/src/game/client/hud_basechat.cpp
Inspired by the original while maintaining new features
Had to bring in some files from source 2013 mp to change some values, hence the large number of lines
- fixes #448
> Chat box old style, original font

- .github/workflows/cibuild.yml
See if making upload on tag/release works
nullsystem/neo Test action: https://github.com/nullsystem/neo/actions/runs/11305355704
nullsystem/neo Test release: https://github.com/nullsystem/neo/releases/tag/v99.99TAGCITESTv2
* fixes #698
> CI - Upload on tagged/release

- mp/src/game/shared/basecombatcharacter_shared.cpp
check item flags if weapon can be switched to when ammo exhausted
- fixes #633
> empty weapon vm dissapearing

- mp/src/game/shared/neo/weapons/weapon_knife.cpp
Gives knife attack force, regardless of angle so objects cannot be backstabbed to launch them further.
- fixes #674
> Give knife attack force

- mp/src/game/shared/neo/neo_gamerules.cpp
Move the message down in the code so it is printed once game mode has been voted on already
- fixes #722
> Print <GameMode> ROUND <RoundNumber> STARTED message after game mode has been determined

- mp/src/game/shared/util_shared.cpp
Adds collisions with enemies with sv_neo_collision_enemy_collisions 1
Also allows standing on top of friendlies with sv_neo_collision_friendly_head_collisions 1
value sv_neo_collision_friendly_head_collisions_overlap controls the difference between the bottom of the top player and the top of the bottom player before friendly collisions switch off
> Enemy only collisions

- mp/src/game/client/neo/ui/neo_root.cpp
- mp/src/game/client/neo/ui/neo_root.h
- mp/src/game/client/neo/ui/neo_ui.h
* This just make the UI interaction between the two less anonying, especially for the keybinding tab
* fixes #725
> NeoUI - Save offset states between settings and popup

- mp/src/game/shared/neo/neo_predicted_viewmodel_muzzleflash.cpp
If the view model is hidden, don't draw the muzzle flash
- fixes #711
> Hide muzzle flash for scoped weapons when aimed in

- mp/src/game/client/neo/ui/neo_root_settings.cpp
* Otherwise some video settings will not be properly saved, can be observed by saving, exiting, then loading up
* fixes #752
> NeoUI Settings - call mat_savechanges on save

- mp/src/game/shared/neo/neo_gamerules.cpp
- mp/src/game/shared/neo/neo_gamerules.h
* Switch from ! to . due to SourceMods clash
* Change naming more familiar with the OG:NT sourcemod
* Fixed spectators being listed
* Outputs to chat about .help command on each 3rd center popup
* fixes #705
> Ready up - Change commands a bit

- mp/src/game/shared/Multiplayer/multiplayer_animstate.cpp
Makes classes that don't have animations for certain weapons use placeholder animations instead
- related #687
> Placeholder missing weapon animations

- mp/src/game/client/hl2/c_basehlplayer.h
- mp/src/game/shared/Multiplayer/multiplayer_animstate.cpp
- mp/src/game/shared/hl2mp/hl2mp_playeranimstate.cpp
jinrai recon leg animations when sprinting work in all directions now, all upper body animations play correct animation when idle or walking
- fixes #727
> Animation tweaks

- mp/src/game/client/clientshadowmgr.cpp
Modifying the convar to change the minimum value to 1 doesn't work, installing a changecallback to revert the value change if the new value is 0 doesn't work, so here is the next best solution I can find
- fixes #219
> Disable unfair shadows

- mp/src/game/shared/basecombatweapon_shared.cpp
We don't have holster animations so can just #ifndef neo this out
See #803 for the problem being fixed by this
- fixes #803
> Fix weapons disappearing when dropping very recently switched to guns

- mp/src/game/client/neo/ui/neo_hud_ghost_marker.cpp
Ghost distance marker when someone else is carrying the ghost is handled elsewhere so can just clear this string here if the ghost is being carried.
- fixes #784
> clear ghost distance

- mp/src/game/shared/baseplayer_shared.h
12 seconds death animation time
- fixes #794
> Enforce fade to black

- mp/game/neo/resource/ClientScheme.res
Was bugging me. Text looks ugly & out of place otherwise
> game_text consistent with hud font

- mp/src/game/client/game_controls/SpectatorGUI.cpp
- mp/src/game/client/neo/ui/neo_hud_compass.cpp
- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
move spectator gui position up, move other elements even higher so they stay above spectator gui
- fixes #782
> Scope hiding spectator gui

- mp/src/game/client/CMakeLists.txt
Required for env_screeneffect to function correctly
> Add episodic_screenspaceeffects to compile

- mp/src/game/client/neo/ui/neo_root.cpp
- mp/src/game/client/neo/ui/neo_root.h
- mp/src/game/client/neo/ui/neo_root_settings.cpp
Ensure button width of the main menu root is calculated before the news section of the main menu computes its offset
- fixes #
- related #
> Correct news offset

- mp/src/game/client/vgui_fpspanel.cpp
> Show horizontal and vertical velocity in cl_showpos

- mp/src/game/server/hl2mp/hl2mp_player.cpp
- mp/src/game/shared/neo/weapons/weapon_supa7.cpp
> Fix supa slug pen and slug damage after penetrating a surface

- mp/src/game/client/hud_crosshair.cpp
> Correct scoped weapon scope colour

- mp/src/game/shared/gamerules.cpp
Raise map preview camera by 64 units
- fixes #850
> Raise map preview camera position

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/c_neo_player.h
- mp/src/game/server/neo/neo_player.cpp
- mp/src/game/server/neo/neo_player.h
- mp/src/game/shared/gamemovement.cpp
Agiel's fix to #757
- fixes #757
> Slow down player when moving backwards correctly

- mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp
- mp/src/game/client/hl2mp/hud_deathnotice.cpp
NEOASSETS PR ---->https://github.com/NeotokyoRebuild/neoAssets/pull/19 <----
Adds weapon specific killfeed icons.
- fixes #193
> KillFeed weapon icons

- mp/game/neo/scripts/kb_act.lst
- mp/src/game/client/in_main.cpp
can toggle walk, can switch back to hold to walk and still have it work if walking is already toggled on, fixes to sprinting when walking.
- fixes #786
> Toggle Walk

- mp/src/game/server/neo/neo_detpack.cpp
> detpacks don't collide with players

- mp/src/game/client/neo/c_neo_player.cpp
- mp/src/game/client/neo/ui/neo_root.cpp
Don't show selection menus and don't record neo_toggleconsole command for demos
> Don't record commands in demos

- mp/src/game/shared/neo/neo_gamerules.cpp
not sure what to do about neo_round_limit
- fixes #706
> single command for comp mode

- mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> players not put in squad by default

- mp/src/game/client/hud_crosshair.cpp
use spectate target as player if local player is an observer
-fixes #912
-fixes #909
> IFF Crosshair showing up too often and crosshair flickering in spectate

- game/neo/scripts/HudLayout.res
- game/neo/scripts/mod_textures.txt
> Original voice Icon

- src/game/shared/util_shared.cpp
One command to control collision method, Bitwise AND, better description to reflect actual behavior (Boosting already worked both on enemies and friendlies regardless of enemy only collision).
Collision options are ordered in terms of how disruptive they are, with enemy only collisions considered more disruptive than boosting, and the combination of the two being the most disruptive.
> player collisions single command

- src/game/server/neo/neo_detpack.cpp
Fixes https://discord.com/channels/1235346473827434517/1235349179296120946/1347227822783074406
> Set detpack parent when settled

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Corrected syntax of the issue/feature templates. Simplified the bug reporting template as most of the fields were unnecessary and can be asked when needed.
> Update issue template

- src/game/client/c_playerresource.cpp
- src/game/client/cdll_client_int.cpp
- src/game/client/clientmode_shared.cpp
- src/game/client/hud_basechat.cpp
- src/game/client/hud_crosshair.cpp
- src/game/client/neo/c_neo_player.cpp
- src/game/client/neo/game_controls/neo_loadoutmenu.cpp
- src/game/client/neo/ui/neo_hud_ammo.cpp
- src/game/client/neo/ui/neo_hud_childelement.cpp
- src/game/client/neo/ui/neo_hud_childelement.h
- src/game/client/neo/ui/neo_hud_compass.cpp
- src/game/client/neo/ui/neo_hud_crosshair.cpp
- src/game/client/neo/ui/neo_hud_crosshair.h
- src/game/client/neo/ui/neo_hud_friendly_marker.cpp
- src/game/client/neo/ui/neo_hud_ghost_cap_point.cpp
- src/game/client/neo/ui/neo_hud_ghost_marker.cpp
- src/game/client/neo/ui/neo_hud_health_thermoptic_aux.cpp
- src/game/client/neo/ui/neo_hud_round_state.cpp
- src/game/client/neo/ui/neo_hud_worldpos_marker.cpp
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_root_settings.cpp
- src/game/client/neo/ui/neo_root_settings.h
- src/game/client/neo/ui/neo_scoreboard.cpp
- src/game/server/neo/neo_client.cpp
- src/game/server/neo/neo_dm_spawn.cpp
- src/game/server/neo/neo_player.cpp
- src/game/shared/neo/neo_gamerules.cpp
- src/game/shared/neo/neo_gamerules.h
- src/game/shared/neo/neo_version.cpp
- src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
Turn it all to `cl_neo`/`sv_neo`, even `mp_neo` -> `sv_neo`
* fixes #1004
> Make cl_neo/sv_neo consistent convar namings

- src/public/bspflags.h
> water splashes

- game/neo/resource/neo_ui/Neo_ClassMenu.res
- game/neo/resource/neo_ui/Neo_LoadoutMenu_Dev.res
- game/neo/resource/neo_ui/Neo_TeamMenu.res
- src/game/client/CMakeLists.txt
- src/game/client/neo/game_controls/neo_button.cpp
- src/game/client/neo/game_controls/neo_button.h
- src/game/client/neo/game_controls/neo_classmenu.cpp
- src/game/client/neo/game_controls/neo_classmenu.h
- src/game/client/neo/game_controls/neo_loadoutmenu.cpp
- src/game/client/neo/game_controls/neo_loadoutmenu.h
- src/game/client/neo/game_controls/neo_teammenu.cpp
- src/game/client/neo/game_controls/neo_teammenu.h
> fine here's your neo button

- src/game/shared/neo/neo_gamerules.cpp
> update restoredinfos on round start instead of round end

- src/game/shared/neo/neo_predicted_viewmodel.cpp
Inverts lean angle direction when using cl_righthand 0 and adds an offset when leaning in problematic direction
- fixes #961
> Viewmodel only lean move gun out of face

- src/game/client/hl2mp/c_hl2mp_player.cpp
- src/game/client/in_main.cpp
- src/game/client/in_main.h
- src/game/client/neo/c_neo_player.cpp
- src/game/server/neo/neo_player.cpp
check if should stop sprint server side and raise sprint button if held and sprint is stopped
- fixes #981
> cancel sprint if cannot sprint, check if should stop sprint server side

- src/game/client/hud_crosshair.cpp
> fix no crosshair in spectate

- src/game/client/smoke_fog_overlay.h
- src/game/server/neo/neo_smokegrenade.cpp
adds smoke particle definitions from source sdk 2006
https://github.com/user-attachments/assets/81e1e822-5f51-41b0-8eff-02150611339c
- fixes #977
> OG Smoke Particles

- src/game/client/fx_blood.cpp
- src/game/server/neo/neo_player.cpp
I'm not confident this will solve the issue, but its worth a try, also cleans up some of the code and adds missing extra blood on gibbing
- related #918
> Drop player weapons after ragdoll creation

- src/game/shared/neo/neo_predicted_viewmodel.cpp
- src/game/shared/neo/weapons/weapon_detpack.cpp
- src/game/shared/neo/weapons/weapon_detpack.h
- src/game/shared/neo/weapons/weapon_grenade.cpp
- src/game/shared/neo/weapons/weapon_grenade.h
- src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
- src/game/shared/neo/weapons/weapon_smokegrenade.cpp
- src/game/shared/neo/weapons/weapon_smokegrenade.h
-fixes #995
-fixes #988
-fixes #997
> Grenade sprint viewmodel animations fix, assert when spamming grenade throw fix, change detpack worldmodel to detremote on tossing the detpack

- src/game/client/neo/ui/neo_hud_startup_sequence.cpp
- src/game/client/neo/ui/neo_hud_startup_sequence.h
> don't show if spectating

- README.md
- game/neo/steam.inf
- src/game/shared/neo/neo_gamerules.h
* Updated instructions for 64-bits NT;RE
* Note about missing files from dedicated servers
* Added section about Steam networking
* Website release note should be updated to say that Linux dedicated actually works after all
* Also removed `-multilib` package instructions for Linux
* fixes #931
> Update server instructions for 64-bits NT;RE

- src/game/client/neo/game_controls/neo_teammenu.cpp
- src/game/server/neo/neo_player.cpp
> weapon switching problem

- src/game/client/c_env_projectedtexture.cpp
- src/game/client/clientshadowmgr.cpp
Fixes parenting of the entity + culling
> Projected texture fixes

- game/neo/scripts/soundscapes_ntre_bullet_tdm.txt
- game/neo/scripts/soundscapes_ntre_dawn_ctg.txt
- game/neo/scripts/soundscapes_ntre_disengage_ctg.txt
- game/neo/scripts/soundscapes_ntre_dusk_ctg.txt
- game/neo/scripts/soundscapes_ntre_engage_ctg.txt
- game/neo/scripts/soundscapes_ntre_ghost_ctg.txt
- game/neo/scripts/soundscapes_ntre_isolation_ctg.txt
- game/neo/scripts/soundscapes_ntre_redlight_ctg.txt
- game/neo/scripts/soundscapes_ntre_ridgeline_ctg.txt
- game/neo/scripts/soundscapes_ntre_rise_ctg.txt
- game/neo/scripts/soundscapes_ntre_sentinel_ctg.txt
- game/neo/scripts/soundscapes_ntre_shrine_ctg.txt
- game/neo/scripts/soundscapes_ntre_skyline_ctg.txt
- game/neo/scripts/soundscapes_ntre_tarmac_ctg.txt
- game/neo/scripts/soundscapes_ntre_vtol_ctg.txt
Soundscapes to accompany https://github.com/NeotokyoRebuild/neoAssets/pull/33
> Base maps soundscapes

- .gitignore
To accompany https://github.com/NeotokyoRebuild/neoAssets/pull/34
> Detail.vbsp gitignore

- src/game/client/neo/c_neo_player.cpp
- src/game/client/neo/game_controls/neo_classmenu.cpp
- src/game/client/neo/game_controls/neo_loadoutmenu.cpp
- src/game/client/neo/game_controls/neo_teammenu.cpp
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_root_settings.h
> Class selection skipped when not in a game team before team selection

- game/neo/gameinfo.txt
- src/game/client/c_te_playerdecal.cpp
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_root.h
- src/game/client/neo/ui/neo_root_settings.cpp
Some bit of tweaking around with c_te_playerdecal.cpp and gameinfo.txt to get it to work properly. Tested with two computers with steam networking server. Also prevent spray change during in-game and moved `IsInGame` to just a function.
* fixes #1040
> Fix non-local player's spray not showing up

- src/game/client/c_effects.cpp
Rain now creates splash particles when hitting a surface, and reacts to env_wind rather than two commands that could not be utilised outside of cheats.
Rain splash code provided by [Tony Sergi](https://developer.valvesoftware.com/wiki/User:Omega)
neoAssets >>> https://github.com/NeotokyoRebuild/neoAssets/pull/39
> Rain improvements

- src/game/client/neo/ui/neo_loading.cpp
- src/game/client/neo/ui/neo_loading.h
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_root.h
- src/game/client/neo/ui/neo_root_serverbrowser.cpp
- src/game/client/neo/ui/neo_root_serverbrowser.h
- src/game/client/neo/ui/neo_ui.cpp
- src/game/client/neo/ui/neo_ui.h
* Server detail's and password layout fixed
* Server detail's player list improved, now include player's score and time in the server
* Now a table with sorting ability
* Use `std::sort` over `V_qsort_s` (which seemed a bit broken somewhat)
* Fixed slider mouse drag
* Remove widgets hardcoded cap, now does dynamic allocation
* fixes #1054
> NeoUI - Fix some layouts, improve server detail player list, remove widget cap

- CONTRIBUTING.md
- src/game/shared/neo/neo_gamerules.cpp
* Remove outdated "neopath" in CONTRIBUTING.md
* Ready up center text drop "now"
> Misc. edits

- src/game/client/neo/ui/neo_hud_ghost_beacons.cpp
- src/game/server/neo/neo_player.cpp
> Remove phantom beeps

- src/game/shared/baseentity_shared.cpp
A while back I opened a PR which changed how bullet penetration worked to what I had in mind originally, which is that when hitting an object, a traceline would be made starting inside the object to find a good place to then do a backwards trace from, instead of from a set point 12 hammer units past the bullet entrance. This would theoretically ensure that any really thin walls of a few hammer units in thickness did not get skipped during the bullets trajectory. This worked great for brushes where making a call to UTIL_traceline with the starting position slightly inside of the brush would move the starting position of the traceline along the path it would take until the end of the brush was found. However this does not work for props and hitboxes (and perhaps other objects), where …
> Props Penetrateable again

- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_ui.cpp
- src/game/client/neo/ui/neo_ui.h
* Fix spray files not properly created in Windows
* Omit invalid spray files from shown in the picker and deleter
* Fix image in confirm dialog not showing
* Add flag to NeoUI::Texture
* Replace currently used spray with default lambda if it matches the deleting spray
> Fix NeoUI spray issues

- src/game/shared/neo/neo_gamerules.cpp
* Also change the logic a bit to just count every playing players for both loopback and bot-only logics
- Linux GCC Distro Native Gentoo 14.2.1
* fixes #1092
> Add bot-only skip warmup logic in round start

- src/game/client/neo/ui/neo_root.h
Change the deault map since we've renamed them, also change the default hostname for listenservers.
- fixes #
- related #
> Change default map to one that's available, change default hostname for listen servers

- src/game/client/cdll_client_int.cpp
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/weapon_selection.cpp
Enables developer console and fast weapon switching by default
- related #975
> Enable console and fastswitch by default

- src/game/client/neo/ui/neo_hud_round_state.cpp
- src/game/client/neo/ui/neo_hud_round_state.h
Hides all squad star imagepanels on disconnect
- fixes #1083
> hide all squad star images on disconnect

- src/game/client/neo/c_neo_player.cpp
- src/game/server/neo/neo_player.cpp
- src/game/shared/neo/weapons/weapon_ghost.cpp
transmit m_bCarryingGhost since it can't be predicted client side without some greater refactoring
> Client server speed missmatch when carrying ghost fix

- game/neo/scripts/propdata.txt
Required for props to behave consistently, and as they did in OG
> Propdata file

- src/game/client/glow_outline_effect.cpp
- src/game/shared/gamevars_shared.cpp
> mp_forcecamera disables glow effect for players

- src/game/client/neo/ui/neo_hud_deathnotice.cpp
- src/game/shared/neo/neo_gamerules.cpp
use victim instead of killed in suicide message
- fixes #1103
> Environmental deaths as suicide

- src/game/client/c_baseanimating.cpp
oops
- Linux GCC Native [Arch, g++ (GCC) 15.1.1 20250425]
- fixes #1126
- related #1133
- related #1085
> Hotfix for black viewmodel bug

- src/game/client/neo/ui/neo_hud_friendly_marker.cpp
Stops friendly player marker moving left and right when players are leaning
> Player marker from origin

- README.md
Title. Hopefully can be solved in the steam version
- related #1137
> Tell people how to get the engine tools working

- src/game/client/neo/ui/neo_hud_crosshair.cpp
> Set circle crosshair colour always

- game/neo/scripts/soundscapes_background.txt
- game/neo/scripts/soundscapes_manifest.txt
Title
[neoAssets](https://github.com/NeotokyoRebuild/neoAssets/pull/48)
> Soundscapes for background maps

- src/game/server/bmodels.cpp
Very very specific crash made apparent when using trigger_serverragdoll and this entity
- related #1141
> func_clip_vphysics crash fix

- src/game/shared/basecombatweapon_shared.h
- src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp
- src/game/shared/neo/weapons/weapon_neobasecombatweapon.h
Add vphysics to weapons on activate like how its done in fallthink when weapons are dropped by player
- related #883
Two issues in one
> Weapons vphysics when created with commands

- src/game/client/mp3player.cpp
It kept on happening on startup, don't see much of an issue of ifndef the assert as it works fine anyway
> MP3 music player kept on asserting, just ifndef it out for now

- src/game/client/neo/ui/neo_ui.cpp
- src/game/client/neo/ui/neo_ui.h
* We have left and center, but not right
* Nothing from master using it, but the WIP killer damage HUD will probably use it anyway
* fixes #1220
> NeoUI - Add right-alignment label/button text support

- src/game/client/cdll_client_int.cpp
- src/game/client/neo/ui/neo_loading.cpp
- src/game/client/neo/ui/neo_loading.h
- src/game/client/neo/ui/neo_root.cpp
- src/game/client/neo/ui/neo_root.h
Hides the main menu element when loading a background map. Fades the menu in once loaded in with a delay. Also hides the main menu when joining or creating a server through the main menu
> Ease menu in on game start

- game/neo/scripts/soundscapes_ntre_ballistrade_ctg.txt
- game/neo/scripts/soundscapes_ntre_marketa_ctg.txt
Soundscapes for balli and marketa
[neoAssets](https://github.com/NeotokyoRebuild/neoAssets/pull/61)
> Balli & Marketa Soundscapes

- src/game/client/neo/ui/neo_root_settings.cpp
- src/game/client/neo/ui/neo_root_settings.h
* Add assert to also catch out if it reaches past the array limit
- Linux GCC Distro Native Gentoo
* fixes #1239
> NeoUI - Bump up keybinds array

- src/game/client/neo/ui/neo_ui.cpp
- src/game/client/neo/ui/neo_ui.h
* Refactor layouting related section mostly so it's more workable with the vertical layouting and more clear start-end point during alterting the layouting
* New vertical per row-cell layouting which allows multiple sub-rows used, mostly for label-only decorated visuals
* `xWide` change from multiple ternary to if statements for clearer readability
* Split off from the WIP killer damage HUD and only benefits that PR for now
* Fixed row highlights
- related #1190
- fixes #1246
> NeoUI - Refactor + add vertical per row-cell layout

- src/game/server/CMakeLists.txt
- src/game/server/NextBot/NextBotBehavior.h
- src/game/server/NextBot/Player/NextBotPlayer.h
- src/game/server/NextBot/Player/NextBotPlayerLocomotion.cpp
- src/game/server/neo/bot/behavior/neo_bot_behavior.cpp
- src/game/server/neo/bot/behavior/neo_bot_behavior.h
- src/game/server/neo/bot/neo_bot.cpp
- src/game/server/neo/bot/neo_bot.h
- src/game/server/neo/bot/neo_bot_contextual_query_interface.h
- src/game/server/neo/bot/neo_bot_locomotion.cpp
- src/game/server/neo/bot/neo_bot_locomotion.h
- src/game/server/neo/neo_player.cpp
- src/game/server/neo/neo_player.h
* Just need to flip the logic that sets "walk" action into run action
* Also add some really basic sprinting logic
* Initial implementation of `CNEOBotContextualQueryInterface`, can be expanded further on later, just deal with walking/sprint at the moment
* fixes #1257
> Bots - Make them run/sprint properly + CNEOBotContextualQueryInterface

- src/game/server/neo/bot/neo_bot.cpp
Set some default values for some convars for the bots to stop spam in the console
- fixes #1251
> Default client side only convar values

- README.md
> Linux - document to also copy rename jitte NT directory

- src/game/shared/neo/weapons/weapon_ghost.cpp
- src/game/shared/neo/weapons/weapon_ghost.h
> Fix no ghost pick up sound when picking up weapon with use key while primary weapon in inventory

- game/neo/resource/ui/ScoreBoard.res
- Linux GCC Native [Arch, g++ (GCC) 15.2.1 20250813]
- fixes #1037
> Remove scoreboard borders

- src/game/shared/neo/weapons/weapon_tachi.cpp
> Remove tachi mode switch console message

- game/neo/scripts/soundscapes_ntre_terminal_jgr.txt
https://github.com/NeotokyoRebuild/neoAssets/pull/70
> Terminal soundscapes

- src/game/client/neo/ui/neo_ui.cpp
Fixes the font for the Disconnected menu for clients that have been disconnected from a server.
> Fix Disconnected Menu Prompt
